Repository FuelLabs/fuels-rs, pull requests merged in 2022-03, with the labels that each got.

#109 change author to authors in Forc.toml files
  .gitignore
  fuels-abigen-macro/tests/test_projects/call_empty_return/Forc.toml
  fuels-abigen-macro/tests/test_projects/complex_types_contract/Forc.toml
  fuels-abigen-macro/tests/test_projects/contract_output_test/Forc.toml
  fuels-abigen-macro/tests/test_projects/contract_test/Forc.toml
  fuels-abigen-macro/tests/test_projects/empty-arguments/Forc.toml
  fuels-abigen-macro/tests/test_projects/lib-core/Forc.toml
  fuels-abigen-macro/tests/test_projects/lib-std/Forc.toml
  fuels-abigen-macro/tests/test_projects/library_test/Forc.toml
  fuels-abigen-macro/tests/test_projects/multiple-read-calls/Forc.toml
  fuels-abigen-macro/tests/test_projects/revert_transaction_error/Forc.toml
  fuels-abigen-macro/tests/test_projects/script_test/Forc.toml
  fuels-abigen-macro/tests/test_projects/simple_script/Forc.toml
  fuels-abigen-macro/tests/test_projects/two-structs/Forc.toml
  fuels-contract/Cargo.toml
  fuels-contract/src/contract.rs
  fuels-contract/src/script.rs
Labels: enhancement

#124 Add caching for rust dependencies
  .github/workflows/ci.yml
  .gitignore
  Cargo.lock
Labels: enhancement

#113 feat: connect to already deployed contracts
  Cargo.lock
  README.md
  fuels-abigen-macro/Cargo.toml
  fuels-abigen-macro/tests/harness.rs
  fuels-abigen-macro/tests/test_projects/contract_test/abi.json
  fuels-abigen-macro/tests/test_projects/contract_test/src/main.sw
  fuels-contract/src/contract.rs
  fuels-core/src/code_gen/abigen.rs
  fuels-core/src/code_gen/functions_gen.rs
Labels: enhancement, abigen

#129 feat: add a `connect` method to connect to existing nodes
  fuels-abigen-macro/tests/harness.rs
  fuels-signers/src/provider.rs
Labels: enhancement

#142 docs: fix docs for new contract instantiation
  README.md
  fuels-abigen-macro/README.md
  fuels-abigen-macro/tests/test_projects/two-structs/tests/harness.rs
Labels: documentation

#145 style: fix clippy warnings
  fuels-abi-cli/src/main.rs
  fuels-contract/src/contract.rs
  fuels-contract/src/script.rs
  fuels-core/src/abi_decoder.rs
  fuels-core/src/abi_encoder.rs
  fuels-core/src/lib.rs
  fuels-core/src/source.rs
  fuels-core/src/types.rs
Labels: enhancement, tech-debt

#147 Update to `fuel-core` 0.4
  Cargo.lock
  fuels-abigen-macro/Cargo.toml
  fuels-abigen-macro/tests/test_projects/foo-caller-contract/Cargo.toml
  fuels-abigen-macro/tests/test_projects/foo-contract/Cargo.toml
  fuels-abigen-macro/tests/test_projects/two-structs/Cargo.toml
  fuels-contract/Cargo.toml
  fuels-contract/src/contract.rs
  fuels-core/Cargo.toml
  fuels-signers/Cargo.toml
  fuels-signers/src/lib.rs
  fuels-signers/src/provider.rs
  fuels-signers/src/signature.rs
  fuels-signers/src/util.rs
  fuels-signers/src/wallet.rs
Labels: enhancement

#144 fix: support the new Sway array type format
  fuels-abigen-macro/tests/harness.rs
  fuels-core/src/code_gen/abigen.rs
  fuels-core/src/errors.rs
  fuels-core/src/json_abi.rs
Labels: bug

#149 Rename color to asset ID.
  fuels-core/src/json_abi.rs
  fuels-signers/src/provider.rs
  fuels-signers/src/wallet.rs
Labels: tech-debt

#157 fix: do not output to stdout when `--show-output` is not enabled
  fuels-core/src/code_gen/abigen.rs
Labels: enhancement, tech-debt

#154 fix: remove workaround for unique tx ids
  Cargo.lock
  README.md
  fuels-abigen-macro/tests/harness.rs
  fuels-contract/Cargo.toml
  fuels-contract/src/contract.rs
  fuels-contract/src/errors.rs
  fuels-core/src/code_gen/abigen.rs
  fuels-core/src/code_gen/functions_gen.rs
  fuels-core/src/json_abi.rs
  fuels-core/src/lib.rs
  fuels-signers/src/lib.rs
  fuels-signers/src/provider.rs
  fuels-signers/src/util.rs
  fuels-signers/src/wallet.rs
Labels: enhancement

#158 Support tx parameter overrides
  README.md
  fuels-abigen-macro/tests/harness.rs
  fuels-abigen-macro/tests/test_projects/foo-caller-contract/Cargo.toml
  fuels-abigen-macro/tests/test_projects/foo-contract/Cargo.toml
  fuels-abigen-macro/tests/test_projects/token-ops/Forc.lock
  fuels-abigen-macro/tests/test_projects/token-ops/Forc.toml
  fuels-abigen-macro/tests/test_projects/token-ops/out/debug/token-ops-abi.json
  fuels-abigen-macro/tests/test_projects/token-ops/out/debug/token-ops.bin
  fuels-abigen-macro/tests/test_projects/token-ops/src/main.sw
  fuels-abigen-macro/tests/test_projects/two-structs/Cargo.toml
  fuels-contract/src/contract.rs
  fuels-contract/src/lib.rs
  fuels-contract/src/parameters.rs
  fuels-contract/src/script.rs
  fuels-core/src/abi_decoder.rs
  fuels-core/src/constants.rs
  fuels-core/src/lib.rs
  fuels-signers/src/util.rs
Labels: enhancement

#160 feat: sign transactions before submitting them to the client
  fuels-contract/src/contract.rs
  fuels-signers/src/signature.rs
Labels: enhancement

#161 Handle `ReturnData` for other types
  fuels-abigen-macro/tests/harness.rs
  fuels-abigen-macro/tests/test_projects/large-return-data/out/debug/contract_test-abi.json
  fuels-abigen-macro/tests/test_projects/large-return-data/out/debug/contract_test.bin
  fuels-abigen-macro/tests/test_projects/large-return-data/src/main.sw
  fuels-core/src/code_gen/custom_types_gen.rs
  fuels-core/src/lib.rs
Labels: enhancement, tech-debt

#167 Enable amount/asset forwarding in tx params
  Cargo.lock
  fuels-abigen-macro/tests/harness.rs
  fuels-abigen-macro/tests/test_projects/token-ops/Forc.lock
  fuels-abigen-macro/tests/test_projects/token-ops/out/debug/token-ops-abi.json
  fuels-abigen-macro/tests/test_projects/token-ops/out/debug/token-ops.bin
  fuels-abigen-macro/tests/test_projects/token-ops/src/main.sw
  fuels-contract/src/contract.rs
  fuels-contract/src/parameters.rs
  fuels-core/src/constants.rs
  fuels-signers/src/util.rs
Labels: enhancement

#169 Fix multi-argument contract calls
  fuels-abigen-macro/tests/harness.rs
  fuels-abigen-macro/tests/test_projects/contract_test/out/debug/contract_test-abi.json
  fuels-abigen-macro/tests/test_projects/contract_test/out/debug/contract_test.bin
  fuels-abigen-macro/tests/test_projects/contract_test/src/main.sw
  fuels-contract/src/contract.rs
Labels: bug

#172 Support non-native asset forwarding
  fuels-abigen-macro/tests/harness.rs
  fuels-contract/src/contract.rs
Labels: bug

#173 Support setting variable outputs in contract calls
  fuels-contract/src/contract.rs
Labels: enhancement

#177 Delete Cargo.lock
  Cargo.lock
Labels: bug

#175 feat: Support forwarding amounts of size up to `u64` in contract calls
  fuels-abigen-macro/tests/harness.rs
  fuels-contract/src/contract.rs
  fuels-core/src/constants.rs
Labels: enhancement

#187 Remove extra (incorrect) witness.
  fuels-contract/src/contract.rs
Labels: bug

#191 Allow assets to be forwarded to contracts on calls
  fuels-abigen-macro/tests/harness.rs
  fuels-abigen-macro/tests/test_projects/token-ops/Forc.lock
  fuels-abigen-macro/tests/test_projects/token-ops/Forc.toml
  fuels-abigen-macro/tests/test_projects/token-ops/out/debug/token-ops.bin
  fuels-abigen-macro/tests/test_projects/token-ops/src/main.sw
  fuels-contract/src/contract.rs
Labels: bug

#193 Turn on UTXO validation in tests
  fuels-contract/src/contract.rs
  fuels-signers/src/util.rs
  fuels-signers/src/wallet.rs
Labels: enhancement

#189 feat: differentiate calling and simulating a contract call
  README.md
  fuels-abigen-macro/tests/harness.rs
  fuels-contract/src/contract.rs
  fuels-contract/src/parameters.rs
  fuels-contract/src/script.rs
  fuels-core/src/constants.rs
Labels: enhancement

#194 Accept Sway-native types directly and without wrappers
  fuels-abigen-macro/tests/harness.rs
  fuels-core/src/code_gen/abigen.rs
  fuels-core/src/lib.rs
Labels: enhancement
