Repository FuelLabs/fuels-rs, pull requests merged in 2022-06, with the labels that each got.

#291 docs(examples): add instantiate_client example
  docs/src/getting-started/basics.md
  examples/contracts/src/lib.rs
  packages/fuels/Cargo.toml
  packages/fuels/src/lib.rs
Labels: documentation

#357 feat: add context to InvalidData error
  packages/fuels-contract/src/errors.rs
  packages/fuels-core/src/abi_decoder.rs
  packages/fuels-core/src/errors.rs
  packages/fuels-core/src/json_abi.rs
  packages/fuels-core/src/types.rs
Labels: tech-debt

#356 Add support for custom types in arrays and tuples
  .github/workflows/ci.yml
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-abigen-macro/tests/test_projects/contract_test/src/main.sw
  packages/fuels-abigen-macro/tests/test_projects/tuples/src/main.sw
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/code_gen/custom_types_gen.rs
  packages/fuels-core/src/code_gen/functions_gen.rs
  packages/fuels-core/src/json_abi.rs
  packages/fuels-types/src/lib.rs
Labels: enhancement, abigen, breaking

#366 Add support for Sway-native types wrapped in custom types
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-abigen-macro/tests/test_projects/sway_native_types/.gitignore
  packages/fuels-abigen-macro/tests/test_projects/sway_native_types/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/sway_native_types/src/main.sw
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/code_gen/custom_types_gen.rs
  packages/fuels-core/src/lib.rs
  packages/fuels/src/lib.rs
Labels: bug, abigen

#370 refactor: remove redundant `fuels_contract::errors` mod
  packages/fuels-contract/src/errors.rs
  packages/fuels-contract/src/lib.rs
Labels: enhancement, tech-debt

#374 ci: update forc to 0.15.1
  .github/workflows/ci.yml
  packages/fuels-abigen-macro/tests/test_projects/auth_testing_contract/src/main.sw
  packages/fuels-abigen-macro/tests/test_projects/token_ops/src/main.sw
  scripts/build-test-projects/src/main.rs
Labels: ci

#378 Use SLIP-44 coin type in derivation path.
  examples/wallets/src/lib.rs
  packages/fuels-signers/src/wallet.rs
Labels: enhancement, tech-debt

#379 fix: improve fn signature generation for tuples
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-abigen-macro/tests/test_projects/tuples/src/main.sw
  packages/fuels-core/src/code_gen/functions_gen.rs
Labels: bug, abigen

#380 fix: excess newline in test builder
  scripts/build-test-projects/src/main.rs
Labels: bug

#384 Rename native -> base asset.
  docs/src/getting-started/basics.md
  docs/src/getting-started/wallets.md
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-contract/src/contract.rs
  packages/fuels-core/src/constants.rs
  packages/fuels-core/src/parameters.rs
  packages/fuels-signers/src/lib.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/src/lib.rs
Labels: breaking

#373 feat: extend abi json cli tests to cover expected errors
  packages/fuels-core/src/json_abi.rs
Labels: enhancement, testing

#361 Enum encoding
  .github/workflows/ci.yml
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-abigen-macro/tests/test_projects/enum_as_input/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/enum_as_input/src/main.sw
  packages/fuels-abigen-macro/tests/test_projects/enum_encoding/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/enum_encoding/src/main.sw
  packages/fuels-abigen-macro/tests/test_projects/use_enum_input/src/main.sw
  packages/fuels-contract/src/contract.rs
  packages/fuels-core/src/abi_decoder.rs
  packages/fuels-core/src/abi_encoder.rs
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/code_gen/custom_types_gen.rs
  packages/fuels-core/src/code_gen/functions_gen.rs
  packages/fuels-core/src/constants.rs
  packages/fuels-core/src/encoding_utils.rs
  packages/fuels-core/src/json_abi.rs
  packages/fuels-core/src/lib.rs
  packages/fuels-core/src/types.rs
  packages/wasm-tests/src/lib.rs
Labels: bug

#385 fix: check file type
  packages/fuels-contract/Cargo.toml
  packages/fuels-contract/src/contract.rs
Labels: enhancement

#391 fix: fn selector for unwrapped arrays
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-core/src/json_abi.rs
Labels: bug

#392 fix: do not modify custom type names
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-abigen-macro/tests/test_projects/enum_as_input/src/main.sw
  packages/fuels-core/src/code_gen/custom_types_gen.rs
  packages/fuels-core/src/code_gen/functions_gen.rs
Labels: bug

#394 fix: do not modify inner enum name in a nested enum
  packages/fuels-core/src/code_gen/custom_types_gen.rs
Labels: bug

#386 Actually forward gas on contract call
  docs/src/getting-started/basics.md
  examples/contracts/src/lib.rs
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-abigen-macro/tests/test_projects/msg_amount/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/msg_amount/src/main.sw
  packages/fuels-contract/src/contract.rs
  packages/fuels-contract/src/script.rs
  packages/fuels-core/src/constants.rs
  packages/fuels-core/src/parameters.rs
Labels: enhancement

#355 feat: introduce the option of using `fuel-core` binary instead of `fuel-core` library
  Cargo.toml
  examples/contracts/Cargo.toml
  examples/contracts/src/lib.rs
  examples/wallets/src/lib.rs
  packages/fuels-abigen-macro/Cargo.toml
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-signers/Cargo.toml
  packages/fuels-signers/src/lib.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/Cargo.toml
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/node.rs
  packages/fuels-test-helpers/src/script.rs
  packages/fuels-test-helpers/src/signers.rs
  packages/fuels/Cargo.toml
  packages/fuels/src/lib.rs
Labels: enhancement

#393 add abigen to fuels Cargo.Toml
  docs/src/getting-started/setup.md
  docs/src/getting-started/type-safe-bindings.md
  examples/contracts/Cargo.toml
  examples/contracts/src/lib.rs
  packages/fuels-abigen-macro/src/lib.rs
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels/src/lib.rs
Labels: abigen, breaking

#398 docs: migrate all examples
  Cargo.toml
  docs/src/getting-started/basics.md
  docs/src/getting-started/type-safe-bindings.md
  docs/src/getting-started/wallets.md
  docs/src/workspaces/fuels-abigen-macro.md
  examples/contracts/src/lib.rs
  examples/rust_bindings/Cargo.toml
  examples/rust_bindings/src/abi.json
  examples/rust_bindings/src/lib.rs
  examples/rust_bindings/src/rust_bindings_formatted.rs
  examples/wallets/src/lib.rs
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-abigen-macro/tests/test_projects/contract_test/src/main.sw
  packages/fuels-abigen-macro/tests/test_projects/token_ops/src/main.sw
  packages/fuels-contract/src/contract.rs
  packages/fuels-core/src/constants.rs
  packages/fuels-signers/src/provider.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/src/script.rs
Labels: testing, The Book

#409 Encoding of an enum with all unit variants (#390)
  .github/workflows/ci.yml
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-abigen-macro/tests/test_projects/call_empty_return/src/main.sw
  packages/fuels-abigen-macro/tests/test_projects/complex_types_contract/src/main.sw
  packages/fuels-abigen-macro/tests/test_projects/contract_test/src/main.sw
  packages/fuels-abigen-macro/tests/test_projects/enum_encoding/src/main.sw
  packages/fuels-abigen-macro/tests/test_projects/foo_caller_contract/src/main.sw
  packages/fuels-abigen-macro/tests/test_projects/multiple_read_calls/src/main.sw
  packages/fuels-abigen-macro/tests/test_projects/nested_enums/src/main.sw
  packages/fuels-contract/src/contract.rs
  packages/fuels-core/src/abi_decoder.rs
  packages/fuels-core/src/abi_encoder.rs
  packages/fuels-core/src/code_gen/functions_gen.rs
  packages/fuels-core/src/encoding_utils.rs
  packages/fuels-core/src/json_abi.rs
  packages/fuels-core/src/lib.rs
Labels: bug

#416 fix: custom types containing reserved keyword
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-abigen-macro/tests/test_projects/nested_structs/src/main.sw
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/constants.rs
Labels: bug

#417 fix: broken crate publishing CI due to abigen feature flag
  packages/fuels-abigen-macro/Cargo.toml
Labels: ci

#422 refactor: change the launch functions and wallet setup
  examples/contracts/src/lib.rs
  examples/rust_bindings/src/lib.rs
  examples/wallets/src/lib.rs
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-contract/src/contract.rs
  packages/fuels-test-helpers/src/script.rs
  packages/fuels-test-helpers/src/signers.rs
Labels: tech-debt, breaking

#423 docs: typos and small improvements
  docs/src/getting-started/basics.md
  docs/src/getting-started/type-safe-bindings.md
  docs/src/getting-started/wallets.md
Labels: documentation

#426 ci: gh checkout v2 -> v3
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
Labels: ci

#427 refactor: tests return Result<> when applicable
  examples/contracts/src/lib.rs
  examples/wallets/src/lib.rs
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-core/src/abi_decoder.rs
  packages/fuels-core/src/abi_encoder.rs
  packages/fuels-core/src/encoding_utils.rs
  packages/fuels-core/src/json_abi.rs
  packages/fuels-signers/src/lib.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/script.rs
Labels: tech-debt

#399 Multi-call
  docs/src/getting-started/basics.md
  examples/contracts/src/lib.rs
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-contract/src/contract.rs
  packages/fuels-contract/src/script.rs
  packages/fuels/src/lib.rs
Labels: enhancement

#431 Improve devx by providing shortcuts to decode bytes into contract types.
  docs/src/getting-started/type-safe-bindings.md
  docs/src/testing/index.md
  examples/contracts/src/lib.rs
  examples/rust_bindings/src/lib.rs
  examples/wallets/src/lib.rs
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/code_gen/custom_types_gen.rs
  packages/fuels-core/src/json_abi.rs
  packages/fuels-core/src/lib.rs
Labels: enhancement

#440 fix: cargo build with `--no-default-features` flag
  .github/workflows/ci.yml
  packages/fuels-test-helpers/src/lib.rs
Labels: bug
