Repository FuelLabs/fuels-rs, pull requests merged in 2022-12, with the labels that each got.

#700 feat: get message proof
  docs/src/wallets/transferring-assets.md
  examples/wallets/src/lib.rs
  packages/fuels-signers/src/provider.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-types/src/block.rs
  packages/fuels-types/src/lib.rs
  packages/fuels-types/src/message_proof.rs
Labels: enhancement

#720 feat: add predicate data encoder method
  docs/src/SUMMARY.md
  docs/src/predicates/predicate-data.md
  examples/predicates/src/lib.rs
  packages/fuels-contract/src/predicate.rs
  packages/fuels/tests/predicates/predicate_data_example/.gitignore
  packages/fuels/tests/predicates/predicate_data_example/Forc.toml
  packages/fuels/tests/predicates/predicate_data_example/src/main.sw
Labels: documentation, package:predicates

#722 Fix some broken links to the Sway book
  docs/src/contracts/the-json-abi-file.md
  docs/src/getting-started/contracts.md
  docs/src/getting-started/predicates.md
  docs/src/getting-started/setup.md
Labels: bug, documentation

#707 feat!: convert client types to fuels types
  examples/wallets/src/lib.rs
  packages/fuels-contract/src/contract.rs
  packages/fuels-contract/src/contract_calls_utils.rs
  packages/fuels-contract/src/execution_script.rs
  packages/fuels-signers/src/lib.rs
  packages/fuels-signers/src/provider.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/node.rs
  packages/fuels-test-helpers/src/signers.rs
  packages/fuels-test-helpers/src/utils.rs
  packages/fuels-types/Cargo.toml
  packages/fuels-types/src/bech32.rs
  packages/fuels-types/src/block.rs
  packages/fuels-types/src/chain_info.rs
  packages/fuels-types/src/coin.rs
  packages/fuels-types/src/lib.rs
  packages/fuels-types/src/message.rs
  packages/fuels-types/src/message_proof.rs
  packages/fuels-types/src/node_info.rs
  packages/fuels-types/src/resource.rs
  packages/fuels-types/src/transaction_response.rs
  packages/fuels/tests/providers.rs
  packages/fuels/tests/wallets.rs
Labels: enhancement, breaking

#728 bug: asset ids not collated properly.
  packages/fuels-contract/src/contract_calls_utils.rs
Labels: bug

#744 feat: Add `attributes` to `ABIFunction`
  packages/fuels-core/src/code_gen/functions_gen.rs
  packages/fuels-types/src/lib.rs
Labels: abigen

#747 feat: build test projects concurrently by default
  .github/workflows/ci.yml
  scripts/test-projects/src/cli.rs
Labels: testing
