Repository FuelLabs/fuels-rs, pull requests merged in 2022-04, with the labels that each got.

#196 Implement Detokenize trait for Address
  fuels-core/src/lib.rs
Labels: bug

#198 refactor: reorganize `Errors` inside `fuels-core`
  fuels-abigen-macro/tests/harness.rs
  fuels-contract/src/contract.rs
  fuels-contract/src/errors.rs
  fuels-contract/src/lib.rs
  fuels-contract/src/script.rs
  fuels-core/src/errors.rs
  fuels-signers/src/wallet.rs
Labels: tech-debt

#199 feat: add `maturity` field to `TxParameters` struct
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-contract/src/parameters.rs
  packages/fuels-core/src/constants.rs
Labels: enhancement

#203 Compute calldata offset on `B256` argument
  .gitattributes
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-abigen-macro/tests/test_projects/auth_testing_abi/Forc.lock
  packages/fuels-abigen-macro/tests/test_projects/auth_testing_abi/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/auth_testing_abi/out/debug/auth_testing_abi.bin
  packages/fuels-abigen-macro/tests/test_projects/auth_testing_abi/src/main.sw
  packages/fuels-abigen-macro/tests/test_projects/auth_testing_contract/Forc.lock
  packages/fuels-abigen-macro/tests/test_projects/auth_testing_contract/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/auth_testing_contract/out/debug/auth_testing_contract-abi.json
  packages/fuels-abigen-macro/tests/test_projects/auth_testing_contract/out/debug/auth_testing_contract.bin
  packages/fuels-abigen-macro/tests/test_projects/auth_testing_contract/src/main.sw
  packages/fuels-contract/src/contract.rs
Labels: bug

#219 Add `fuels-types` minimal crate for declaring serializable ABI types. Resolves the cycle between `fuels-rs` and `sway` repos.
  .github/workflows/ci.yml
  Cargo.toml
  packages/fuels-contract/Cargo.toml
  packages/fuels-core/Cargo.toml
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/code_gen/custom_types_gen.rs
  packages/fuels-core/src/code_gen/functions_gen.rs
  packages/fuels-core/src/json_abi.rs
  packages/fuels-types/Cargo.toml
  packages/fuels-types/src/lib.rs
  tools/fuels-abi-cli/Cargo.toml
  tools/fuels-abi-cli/src/main.rs
Labels: enhancement, tech-debt

#227 Move to 2021 Rust #137
  Cargo.toml
  packages/fuels-abigen-macro/Cargo.toml
  packages/fuels-contract/Cargo.toml
  packages/fuels-core/src/json_abi.rs
  tools/fuels-abi-cli/Cargo.toml
Labels: tech-debt

#228 Refactor: make a `fuels-test-helpers` crate
  Cargo.toml
  packages/fuels-core/src/constants.rs
  packages/fuels-rs/Cargo.toml
  packages/fuels-rs/src/lib.rs
  packages/fuels-signers/Cargo.toml
  packages/fuels-signers/src/lib.rs
  packages/fuels-signers/src/util.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/Cargo.toml
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/signers.rs
Labels: tech-debt

#213 feat: support `Tuple` in `Enum` and `Enum` in `Tuple`
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-abigen-macro/tests/test_projects/enum_inside_struct/Forc.lock
  packages/fuels-abigen-macro/tests/test_projects/enum_inside_struct/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/enum_inside_struct/out/debug/enum_inside_struct-abi.json
  packages/fuels-abigen-macro/tests/test_projects/enum_inside_struct/out/debug/enum_inside_struct.bin
  packages/fuels-abigen-macro/tests/test_projects/enum_inside_struct/src/main.sw
  packages/fuels-abigen-macro/tests/test_projects/struct_inside_enum/Forc.lock
  packages/fuels-abigen-macro/tests/test_projects/struct_inside_enum/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/struct_inside_enum/out/debug/struct_inside_enum-abi.json
  packages/fuels-abigen-macro/tests/test_projects/struct_inside_enum/out/debug/struct_inside_enum.bin
  packages/fuels-abigen-macro/tests/test_projects/struct_inside_enum/src/main.sw
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/code_gen/custom_types_gen.rs
  packages/fuels-core/src/code_gen/functions_gen.rs
  packages/fuels-core/src/constants.rs
  packages/fuels-core/src/json_abi.rs
  packages/fuels-core/src/lib.rs
Labels: enhancement

#229 refactor: implement helper methods on `Property` types
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/code_gen/custom_types_gen.rs
  packages/fuels-core/src/code_gen/functions_gen.rs
  packages/fuels-core/src/constants.rs
  packages/fuels-core/src/json_abi.rs
  packages/fuels-types/Cargo.toml
  packages/fuels-types/src/lib.rs
Labels: tech-debt

#242 Rename `fuels-rs` crate to `fuels`
  packages/fuels-abigen-macro/Cargo.toml
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-rs/Cargo.toml
  packages/fuels-rs/src/lib.rs
Labels: tech-debt

#238 feat: decode `LOGD` data in `CallResponse`
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-abigen-macro/tests/test_projects/contract_logdata/.gitignore
  packages/fuels-abigen-macro/tests/test_projects/contract_logdata/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/contract_logdata/src/main.sw
  packages/fuels-contract/src/contract.rs
  packages/fuels-core/src/lib.rs
Labels: enhancement
