Repository FuelLabs/fuels-rs, pull requests merged in 2022-10, with the labels that each got.

#597 feat: vector input support
  .github/workflows/ci.yml
  docs/src/SUMMARY.md
  docs/src/types/custom_types.md
  docs/src/types/vectors.md
  packages/fuels-contract/src/contract.rs
  packages/fuels-contract/src/script.rs
  packages/fuels-core/src/abi_decoder.rs
  packages/fuels-core/src/abi_encoder.rs
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/code_gen/function_selector.rs
  packages/fuels-core/src/code_gen/functions_gen.rs
  packages/fuels-core/src/code_gen/resolved_type.rs
  packages/fuels-core/src/lib.rs
  packages/fuels-core/src/tokenizer.rs
  packages/fuels-core/src/types/native.rs
  packages/fuels-types/Cargo.toml
  packages/fuels-types/src/lib.rs
  packages/fuels-types/src/param_types.rs
  packages/fuels/tests/harness.rs
  packages/fuels/tests/test_projects/vectors/Forc.toml
  packages/fuels/tests/test_projects/vectors/src/data_structures.sw
  packages/fuels/tests/test_projects/vectors/src/eq_impls.sw
  packages/fuels/tests/test_projects/vectors/src/main.sw
  packages/fuels/tests/test_projects/vectors/src/utils.sw
  packages/wasm-tests/src/lib.rs
Labels: enhancement

#582 Parse logged types
  docs/src/SUMMARY.md
  docs/src/calling-contracts/call-response.md
  docs/src/calling-contracts/logs.md
  examples/contracts/src/lib.rs
  packages/fuels-contract/src/contract.rs
  packages/fuels-core/src/code_gen.rs
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/code_gen/custom_types.rs
  packages/fuels-core/src/code_gen/custom_types/utils.rs
  packages/fuels-types/src/lib.rs
  packages/fuels/tests/harness.rs
  packages/fuels/tests/test_projects/logged_types/Forc.toml
  packages/fuels/tests/test_projects/logged_types/src/main.sw
  packages/fuels/tests/test_projects/logging/src/main.sw
  packages/wasm-tests/src/lib.rs
  scripts/build-test-projects/src/main.rs
Labels: enhancement

#611 fix: receipt parsing
  packages/fuels-contract/src/contract.rs
  packages/fuels/tests/harness.rs
  packages/fuels/tests/test_projects/foo_caller_contract/src/main.sw
Labels: bug

#610 feat!: add `Option<Provider>` as parameter in run_compiled_script
  packages/fuels-test-helpers/src/script.rs
Labels: enhancement

#614 Fix: change transfer_to_output to transfer_to_address
  .github/workflows/ci.yml
  docs/src/calling-contracts/variable-outputs.md
  examples/contracts/src/lib.rs
  packages/fuels/tests/test_projects/liquidity_pool/src/main.sw
  packages/fuels/tests/test_projects/token_ops/src/main.sw
Labels: blocked

#621 Some minor cosmetic updates to the SDK Sway tests
  packages/fuels/tests/test_projects/auth_testing_abi/Forc.toml
  packages/fuels/tests/test_projects/auth_testing_abi/src/main.sw
  packages/fuels/tests/test_projects/auth_testing_contract/Forc.toml
  packages/fuels/tests/test_projects/auth_testing_contract/src/main.sw
  packages/fuels/tests/test_projects/call_empty_return/Forc.toml
  packages/fuels/tests/test_projects/call_empty_return/src/main.sw
  packages/fuels/tests/test_projects/complex_types_contract/Forc.toml
  packages/fuels/tests/test_projects/complex_types_contract/src/main.sw
  packages/fuels/tests/test_projects/contract_output_test/Forc.toml
  packages/fuels/tests/test_projects/contract_output_test/src/main.sw
  packages/fuels/tests/test_projects/contract_storage_test/src/main.sw
  packages/fuels/tests/test_projects/contract_test/Forc.toml
  packages/fuels/tests/test_projects/contract_test/src/main.sw
  packages/fuels/tests/test_projects/empty_arguments/src/main.sw
  packages/fuels/tests/test_projects/enum_encoding/src/main.sw
  packages/fuels/tests/test_projects/enum_inside_struct/src/main.sw
  packages/fuels/tests/test_projects/foo_caller_contract/src/main.sw
  packages/fuels/tests/test_projects/foo_contract/src/main.sw
  packages/fuels/tests/test_projects/generics/src/main.sw
  packages/fuels/tests/test_projects/identity/src/main.sw
  packages/fuels/tests/test_projects/large_return_data/Forc.toml
  packages/fuels/tests/test_projects/large_return_data/src/main.sw
  packages/fuels/tests/test_projects/library_test/Forc.toml
  packages/fuels/tests/test_projects/library_test/src/main.sw
  packages/fuels/tests/test_projects/liquidity_pool/Forc.toml
  packages/fuels/tests/test_projects/liquidity_pool/src/main.sw
  packages/fuels/tests/test_projects/logged_types/src/main.sw
  packages/fuels/tests/test_projects/multiple_read_calls/Forc.toml
  packages/fuels/tests/test_projects/multiple_read_calls/src/main.sw
  packages/fuels/tests/test_projects/native_types/Forc.toml
  packages/fuels/tests/test_projects/native_types/src/main.sw
  packages/fuels/tests/test_projects/nested_structs/src/main.sw
  packages/fuels/tests/test_projects/options/src/main.sw
  packages/fuels/tests/test_projects/predicate_signatures/src/main.sw
  packages/fuels/tests/test_projects/predicate_struct/src/main.sw
  packages/fuels/tests/test_projects/results/src/main.sw
  packages/fuels/tests/test_projects/revert_transaction_error/Forc.toml
  packages/fuels/tests/test_projects/revert_transaction_error/src/main.sw
  packages/fuels/tests/test_projects/token_ops/src/main.sw
  packages/fuels/tests/test_projects/transaction_block_height/src/main.sw
  packages/fuels/tests/test_projects/tuples/src/main.sw
  packages/fuels/tests/test_projects/two_structs/Forc.toml
  packages/fuels/tests/test_projects/two_structs/src/main.sw
  packages/fuels/tests/test_projects/type_inside_enum/src/main.sw
  packages/fuels/tests/test_projects/vectors/src/eq_impls.sw
  packages/fuels/tests/test_projects/vectors/src/main.sw
Labels: testing

#616 Test logging generics
  packages/fuels/tests/harness.rs
  packages/fuels/tests/test_projects/logged_types/src/main.sw
Labels: testing

#619 feat: ParamType from TypeApplication/TypeDeclaration in order to generate fn selectors without code generation
  Cargo.toml
  docs/src/SUMMARY.md
  docs/src/debugging/function-selector.md
  examples/debugging/Cargo.toml
  examples/debugging/src/lib.rs
  packages/fuels-core/src/abi_decoder.rs
  packages/fuels-core/src/abi_encoder.rs
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/code_gen/custom_types.rs
  packages/fuels-core/src/code_gen/custom_types/enum_gen.rs
  packages/fuels-core/src/code_gen/custom_types/struct_gen.rs
  packages/fuels-core/src/code_gen/custom_types/utils.rs
  packages/fuels-core/src/code_gen/function_selector.rs
  packages/fuels-core/src/code_gen/resolved_type.rs
  packages/fuels-core/src/lib.rs
  packages/fuels-core/src/types/native.rs
  packages/fuels-types/Cargo.toml
  packages/fuels-types/src/enum_variants.rs
  packages/fuels-types/src/lib.rs
  packages/fuels-types/src/param_types.rs
  packages/fuels-types/src/utils.rs
Labels: enhancement

#613 Variable output estimation
  packages/fuels-contract/src/contract.rs
  packages/fuels-contract/src/script.rs
  packages/fuels-core/src/constants.rs
  packages/fuels/tests/contracts/mod.rs
  packages/fuels/tests/contracts/token_ops/src/main.sw
Labels: enhancement

#639 fix: exiting tests
  docs/src/calling-contracts/logs.md
  docs/src/calling-contracts/other-contracts.md
  docs/src/contracts/the-setup-contract-test-macro.md
  docs/src/contributing/tests-structure.md
  docs/src/testing/chains.md
  docs/src/types/bits256.md
  docs/src/types/custom_types.md
  docs/src/types/string.md
  docs/src/types/vectors.md
  packages/fuels/tests/bindings.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/from_token.rs
  packages/fuels/tests/harness.rs
  packages/fuels/tests/logs.rs
  packages/fuels/tests/predicates.rs
  packages/fuels/tests/providers.rs
  packages/fuels/tests/scripts.rs
  packages/fuels/tests/storage.rs
  packages/fuels/tests/types.rs
  packages/fuels/tests/wallets.rs
Labels: bug

#622 feat!: Enforce Bech32 type-safety on contract instance creation
  docs/src/contracts/interacting-with-contracts.md
  examples/contracts/src/lib.rs
  examples/cookbook/src/lib.rs
  examples/types/src/lib.rs
  packages/fuels-abigen-macro/src/lib.rs
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-types/src/bech32.rs
  packages/fuels/tests/bindings.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/from_token.rs
  packages/fuels/tests/providers.rs
  packages/fuels/tests/storage.rs
  packages/fuels/tests/types.rs
Labels: enhancement

#643 feat: create `Bits256` from hex string
  docs/src/types/bits256.md
  packages/fuels-core/src/types/bits_256.rs
Labels: enhancement, package:core

#568 chore: port and enable flat JSON ABI tests
  packages/fuels-core/src/code_gen/custom_types.rs
  packages/fuels-core/src/code_gen/functions_gen.rs
  packages/fuels-core/src/tokenizer.rs
Labels: tech-debt

#649 fix: doc wording
  docs/src/getting-started/connecting.md
Labels: documentation

#625 feat: concurrently build test projects
  scripts/build-test-projects/Cargo.toml
  scripts/build-test-projects/src/lib.rs
  scripts/build-test-projects/src/main.rs
Labels: testing

#659 docs: implication that returning vectors is a thing.
  docs/src/types/vectors.md
Labels: documentation
