Repository FuelLabs/fuels-rs, pull requests merged in 2022-08, with the labels that each got.

#511 refactor: add an `asset_id` argument to `get_coins` API
  docs/src/providers/querying.md
  examples/providers/src/lib.rs
  examples/wallets/src/lib.rs
  packages/fuels-contract/src/script.rs
  packages/fuels-signers/src/lib.rs
  packages/fuels-signers/src/provider.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/src/signers.rs
Labels: enhancement

#501 feat: launch node with `manual_blocks_enabled` without features
  docs/src/testing/chains.md
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/node.rs
  packages/fuels/tests/harness.rs
Labels: enhancement

#497 contract connect function
  docs/src/SUMMARY.md
  docs/src/calling-contracts/calls-with-different-wallets.md
  examples/contracts/src/lib.rs
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels/tests/harness.rs
Labels: enhancement

#520 Use `fuel-crypto` for secret key generation from mnemonic
  packages/fuels-signers/Cargo.toml
  packages/fuels-signers/src/wallet.rs
Labels: enhancement

#522 Fix error handling in doctest
  packages/fuels-signers/src/wallet.rs
Labels: bug

#526 fix: update Victor's github username in CODEOWNERS
  .github/CODEOWNERS
Labels: bug

#524 Document setup coins
  docs/src/wallets/test-wallets.md
  packages/fuels-test-helpers/src/lib.rs
Labels: documentation, enhancement

#432 feat: add predicate support baseline with tests
  packages/fuels-contract/src/lib.rs
  packages/fuels-contract/src/predicate.rs
  packages/fuels-signers/src/provider.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels/tests/harness.rs
  packages/fuels/tests/test_projects/predicate_address/Forc.toml
  packages/fuels/tests/test_projects/predicate_address/src/main.sw
  packages/fuels/tests/test_projects/predicate_false/Forc.toml
  packages/fuels/tests/test_projects/predicate_false/src/main.sw
  packages/fuels/tests/test_projects/predicate_struct/Forc.toml
  packages/fuels/tests/test_projects/predicate_struct/src/main.sw
  packages/fuels/tests/test_projects/predicate_true/Forc.toml
  packages/fuels/tests/test_projects/predicate_true/src/main.sw
  packages/fuels/tests/test_projects/predicate_u32/Forc.toml
  packages/fuels/tests/test_projects/predicate_u32/src/main.sw
Labels: enhancement, P: medium

#529 fix: script tx input validation bug
  packages/fuels-contract/Cargo.toml
  packages/fuels-contract/src/contract.rs
  packages/fuels-contract/src/script.rs
  packages/fuels/tests/harness.rs
Labels: bug

#523 Cookbook examples
  Cargo.toml
  docs/src/SUMMARY.md
  docs/src/cookbook/cookbook.md
  docs/src/cookbook/custom-chain.md
  docs/src/cookbook/deposit-and-withdraw.md
  docs/src/cookbook/transfer-all-assets.md
  examples/cookbook/Cargo.toml
  examples/cookbook/src/lib.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels/tests/test_projects/liquidity_pool/Forc.toml
  packages/fuels/tests/test_projects/liquidity_pool/src/main.sw
Labels: documentation

#533 feat!: add support to the new flat JSON ABI format
  .github/workflows/ci.yml
  examples/contracts/src/lib.rs
  packages/fuels-abigen-macro/src/lib.rs
  packages/fuels-core/src/abi_encoder.rs
  packages/fuels-core/src/code_gen/custom_types_gen.rs
  packages/fuels-core/src/code_gen/flat_abigen.rs
  packages/fuels-core/src/code_gen/functions_gen.rs
  packages/fuels-core/src/code_gen/mod.rs
  packages/fuels-core/src/json_abi.rs
  packages/fuels-core/src/source.rs
  packages/fuels-core/src/types.rs
  packages/fuels-types/src/bech32.rs
  packages/fuels-types/src/function_selector.rs
  packages/fuels-types/src/lib.rs
  packages/fuels-types/src/parse_param.rs
  packages/fuels-types/src/utils.rs
  packages/fuels/tests/harness.rs
  packages/fuels/tests/takes_ints_returns_bool-flat-abi.json
  packages/fuels/tests/takes_ints_returns_bool.json
Labels: abigen, big, breaking

#540 Distinguish between a `Wallet`'s `Locked` and `Unlocked` states
  docs/src/SUMMARY.md
  docs/src/getting-started/managing-wallets.md
  docs/src/wallets/access.md
  docs/src/wallets/signing.md
  examples/cookbook/src/lib.rs
  examples/providers/src/lib.rs
  examples/rust_bindings/src/rust_bindings_formatted.rs
  examples/wallets/src/lib.rs
  packages/fuels-contract/src/contract.rs
  packages/fuels-contract/src/script.rs
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/code_gen/flat_abigen.rs
  packages/fuels-signers/src/lib.rs
  packages/fuels-signers/src/provider.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/signers.rs
  packages/fuels/src/lib.rs
  packages/fuels/tests/harness.rs
Labels: wallet

#541 feat: add predicate example and docs
  Cargo.toml
  docs/src/SUMMARY.md
  docs/src/getting-started/predicates.md
  docs/src/predicates/send-spend-predicate.md
  examples/predicates/Cargo.toml
  examples/predicates/src/lib.rs
  packages/fuels-signers/src/provider.rs
  packages/fuels/tests/harness.rs
  packages/fuels/tests/test_projects/predicate_signatures/Forc.toml
  packages/fuels/tests/test_projects/predicate_signatures/src/main.sw
Labels: documentation

#546 feat!: bump fuel core to 0.10.1
  .github/workflows/ci.yml
  docs/src/calling-contracts/cost-estimation.md
  examples/contracts/src/lib.rs
  examples/cookbook/src/lib.rs
  packages/fuels-contract/Cargo.toml
  packages/fuels-contract/src/contract.rs
  packages/fuels-contract/src/script.rs
  packages/fuels-core/Cargo.toml
  packages/fuels-core/src/constants.rs
  packages/fuels-core/src/parameters.rs
  packages/fuels-signers/Cargo.toml
  packages/fuels-signers/src/lib.rs
  packages/fuels-signers/src/provider.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/Cargo.toml
  packages/fuels-test-helpers/src/script.rs
  packages/fuels-types/Cargo.toml
  packages/fuels-types/src/lib.rs
  packages/fuels/Cargo.toml
  packages/fuels/tests/harness.rs
Labels: blocked
