Repository FuelLabs/fuels-rs, pull requests merged in 2022-02, with the labels that each got.

#73 refactor: check for types in custom name extraction
  fuels-core/src/code_gen/custom_types_gen.rs
  fuels-core/src/code_gen/functions_gen.rs
Labels: enhancement

#78 Fixes ambiguity on two diff structs with same arg name
  fuels-abigen-macro/tests/harness.rs
  fuels-abigen-macro/tests/test_projects/two-structs/Cargo.toml
  fuels-abigen-macro/tests/test_projects/two-structs/Forc.toml
  fuels-abigen-macro/tests/test_projects/two-structs/abi.json
  fuels-abigen-macro/tests/test_projects/two-structs/src/main.sw
  fuels-abigen-macro/tests/test_projects/two-structs/tests/harness.rs
  fuels-core/src/code_gen/abigen.rs
  fuels-core/src/code_gen/custom_types_gen.rs
  fuels-core/src/code_gen/functions_gen.rs
Labels: bug, abigen

#79 Add --no-verify flag to publish crate action
  .github/workflows/ci.yml
Labels: bug

#83 refactor: add an argument to enable strict argument checking in abigen macro
  fuels-abigen-macro/src/lib.rs
  fuels-abigen-macro/tests/harness.rs
  fuels-abigen-macro/tests/takes_ints_returns_bool.json
  fuels-core/src/code_gen/abigen.rs
  fuels-core/src/code_gen/functions_gen.rs
Labels: tech-debt, abigen

#85 build: bump `fuel-vm` to `0.4` and `fuel-tx` to `0.5`
  Cargo.toml
  fuels-abi-cli/Cargo.toml
  fuels-abigen-macro/Cargo.toml
  fuels-abigen-macro/tests/test_projects/two-structs/Cargo.toml
  fuels-contract/Cargo.toml
  fuels-contract/src/contract.rs
  fuels-contract/tests/calls.rs
  fuels-core/Cargo.toml
  fuels-signers/Cargo.toml
Labels: enhancement

#96 Implement transaction signing
  fuels-signers/src/lib.rs
  fuels-signers/src/signature.rs
  fuels-signers/src/wallet/mod.rs
Labels: enhancement

#100 remove the Url crate from fuels-core
  fuels-core/Cargo.toml
  fuels-core/src/source.rs
Labels: abigen

#95 fix: enable having an empty fourth argument for non-user methods
  fuels-abigen-macro/tests/harness.rs
  fuels-abigen-macro/tests/test_projects/empty-arguments/Forc.toml
  fuels-abigen-macro/tests/test_projects/empty-arguments/abi.json
  fuels-abigen-macro/tests/test_projects/empty-arguments/src/main.sw
  fuels-core/src/code_gen/functions_gen.rs
Labels: bug, abigen

#103 feat: capture error from reverting transactions in the SDK
  fuels-abigen-macro/tests/harness.rs
  fuels-abigen-macro/tests/test_projects/revert_transaction_error/Forc.toml
  fuels-abigen-macro/tests/test_projects/revert_transaction_error/abi.json
  fuels-abigen-macro/tests/test_projects/revert_transaction_error/src/main.sw
  fuels-abigen-macro/tests/test_projects/revert_transaction_error/tests/harness.rs
  fuels-contract/src/contract.rs
  fuels-contract/src/errors.rs
  fuels-contract/src/script.rs
Labels: bug

#110 Send transactions and transfer funds between wallets
  .github/workflows/ci.yml
  fuels-core/src/json_abi.rs
  fuels-signers/Cargo.toml
  fuels-signers/src/lib.rs
  fuels-signers/src/provider.rs
  fuels-signers/src/util.rs
  fuels-signers/src/wallet.rs
  fuels-signers/src/wallet/mod.rs
Labels: enhancement

#117 Update Rust badges to `fuels-contract`
  README.md
Labels: documentation

#120 Remove dev dependency
  fuels-signers/Cargo.toml
Labels: bug
