Repository FuelLabs/fuels-rs, pull requests merged in 2022-05, with the labels that each got.

#240 add new load_sway_contract_with_salt method
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-abigen-macro/tests/test_projects/foo_caller_contract/src/main.sw
  packages/fuels-contract/src/contract.rs
  packages/fuels-contract/src/lib.rs
Labels: enhancement, breaking

#165 Use signing/recovery from fuel_crypto in fuels_signers
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-signers/Cargo.toml
  packages/fuels-signers/src/lib.rs
  packages/fuels-signers/src/provider.rs
  packages/fuels-signers/src/signature.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/Cargo.toml
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/signers.rs
Labels: enhancement

#258 Update the Fuel Rust SDK book to match latest development
  docs/src/getting-started/basics.md
  docs/src/getting-started/setup.md
Labels: documentation

#243 Specify minimum supported Rust version in `fuels-rs` manifest
  .github/workflows/ci.yml
  packages/fuels/Cargo.toml
Labels: enhancement, tech-debt

#261 Update type handling and add support for forc `0.12.x`
  .github/workflows/ci.yml
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-abigen-macro/tests/test_projects/foo_caller_contract/src/main.sw
  packages/fuels-contract/src/contract.rs
  packages/fuels-core/src/lib.rs
Labels: enhancement

#263 test: add tests for `LOGD` decoding in harness
  packages/fuels-abigen-macro/tests/harness.rs
Labels: bug

#259 Add FAQ section
  README.md
Labels: documentation

#269 add load_sway_contract() method refactoring
  packages/fuels-contract/src/contract.rs
Labels: tech-debt

#271 Add `TxParameters` to transfer functionality
  packages/fuels-contract/src/contract.rs
  packages/fuels-contract/src/lib.rs
  packages/fuels-core/src/constants.rs
  packages/fuels-core/src/lib.rs
  packages/fuels-core/src/parameters.rs
  packages/fuels-signers/src/lib.rs
  packages/fuels-signers/src/provider.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels/src/lib.rs
Labels: enhancement

#273 Update getting started/setup doc
  docs/src/getting-started/setup.md
Labels: documentation

#275 feat: support `Enum` type as function argument
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-abigen-macro/tests/test_projects/use_enum_input/.gitignore
  packages/fuels-abigen-macro/tests/test_projects/use_enum_input/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/use_enum_input/src/main.sw
  packages/fuels-contract/src/contract.rs
  packages/fuels-core/src/code_gen/functions_gen.rs
  packages/fuels-core/src/json_abi.rs
Labels: enhancement, abigen

#280 ci: use implicit `sway-std-lib` dependency in tests projects
  packages/fuels-abigen-macro/tests/test_projects/auth_testing_abi/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/auth_testing_contract/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/call_empty_return/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/complex_types_contract/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/contract_test/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/empty_arguments/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/large_return_data/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/library_test/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/multiple_read_calls/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/revert_transaction_error/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/simple_script/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/token_ops/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/tuples/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/two_structs/Forc.toml
Labels: ci

#268 Contract deployment QoL
  docs/src/getting-started/basics.md
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-contract/src/contract.rs
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/code_gen/functions_gen.rs
  packages/fuels-test-helpers/src/signers.rs
Labels: enhancement, breaking

#283 feat: support unit type variants in `Enum`
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-abigen-macro/tests/test_projects/use_enum_input/src/main.sw
  packages/fuels-core/src/abi_decoder.rs
  packages/fuels-core/src/abi_encoder.rs
  packages/fuels-core/src/code_gen/custom_types_gen.rs
  packages/fuels-core/src/json_abi.rs
  packages/fuels-core/src/lib.rs
  packages/fuels-core/src/types.rs
Labels: enhancement, abigen

#284 Fix fuels core dependency
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/code_gen/custom_types_gen.rs
  packages/fuels/src/lib.rs
Labels: bug

#289 Mnemonic and JSON wallets implementation
  docs/src/SUMMARY.md
  docs/src/getting-started/wallets.md
  packages/fuels-signers/Cargo.toml
  packages/fuels-signers/src/wallet.rs
Labels: enhancement, wallet

#293 Setup multiple test wallets and hide SecretKey
  docs/src/getting-started/basics.md
  docs/src/getting-started/wallets.md
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-contract/src/contract.rs
  packages/fuels-core/src/code_gen/functions_gen.rs
  packages/fuels-core/src/constants.rs
  packages/fuels-signers/src/lib.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/Cargo.toml
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/signers.rs
  packages/fuels-test-helpers/src/wallets_config.rs
Labels: enhancement

#297 Add support for forc 0.13
  .github/workflows/ci.yml
  packages/fuels-abigen-macro/tests/test_projects/call_empty_return/src/main.sw
  packages/fuels-abigen-macro/tests/test_projects/complex_types_contract/src/main.sw
  packages/fuels-abigen-macro/tests/test_projects/two_structs/src/main.sw
Labels: enhancement

#305 Added `deploy_with_salt` function
  docs/src/getting-started/basics.md
  packages/fuels-contract/src/contract.rs
Labels: enhancement, good first issue, P: high

#303 Clarify appending variable outputs
  docs/src/getting-started/basics.md
Labels: documentation

#309 Add deploy for loaded contract
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-contract/src/contract.rs
Labels: enhancement

#292 Add logging of all receipts as an option
  docs/src/getting-started/basics.md
  packages/fuels-abigen-macro/Cargo.toml
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-contract/Cargo.toml
  packages/fuels-contract/src/contract.rs
Labels: enhancement

#302 add customisable node config as parameter
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-signers/src/lib.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/signers.rs
Labels: enhancement

#314 chore: add myself as code owner
  .github/CODEOWNERS
Labels: enhancement

#316 Remove unused test project
  packages/fuels-abigen-macro/tests/test_projects/simple_script/.gitignore
  packages/fuels-abigen-macro/tests/test_projects/simple_script/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/simple_script/src/main.sw
Labels: tech-debt

#313 feat: add a balance API
  docs/src/getting-started/wallets.md
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-signers/src/provider.rs
  packages/fuels-signers/src/wallet.rs
Labels: enhancement

#322 fuel-core 0.8 upgrade (predicates)
  docs/src/getting-started/basics.md
  docs/src/getting-started/setup.md
  packages/fuels-abigen-macro/Cargo.toml
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-contract/Cargo.toml
  packages/fuels-contract/src/contract.rs
  packages/fuels-contract/src/script.rs
  packages/fuels-core/Cargo.toml
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-signers/Cargo.toml
  packages/fuels-signers/src/lib.rs
  packages/fuels-signers/src/provider.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/Cargo.toml
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/signers.rs
Labels: breaking

#328 Add more highlighted languages
  docs/theme/highlight.js
Labels: documentation

#330 Fix crypto dep random feature.
  packages/fuels-signers/Cargo.toml
  packages/fuels-test-helpers/Cargo.toml
Labels: bug

#334 Change badges to `fuels`
  README.md
Labels: documentation

#336 Improve setup instructions.
  docs/src/getting-started/setup.md
Labels: documentation

#339 Add ,ignore to rust blocks.
  docs/src/getting-started/basics.md
  docs/src/getting-started/setup.md
  docs/src/getting-started/type-safe-bindings.md
  docs/src/getting-started/wallets.md
  docs/src/workspaces/fuels-abigen-macro.md
Labels: bug, documentation, P: critical

#340 Add link to harness test in docs.
  docs/src/getting-started/basics.md
Labels: documentation

#324 feat: log receipts when contract call panics or reverts
  docs/src/getting-started/basics.md
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-contract/src/contract.rs
  packages/fuels-contract/src/script.rs
  packages/fuels-core/src/errors.rs
Labels: enhancement

#335 Disable feature unification in CI builds
  .github/workflows/ci.yml
  .github/workflows/scripts/verify_tag.sh
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-core/src/json_abi.rs
  packages/fuels-signers/src/wallet.rs
Labels: ci

#349 docs: document `get_spendable_coins` functions
  packages/fuels-signers/src/provider.rs
  packages/fuels-signers/src/wallet.rs
Labels: documentation
