Repository FuelLabs/fuels-rs, pull requests merged in 2022-07, with the labels that each got.

#445 chore: use `concurrency` to cancel previous CI runs
  .github/workflows/ci.yml
Labels: ci

#444 refactor!: move the `Error` type inside `fuels-types` workspace
  packages/fuels-contract/Cargo.toml
  packages/fuels-contract/src/contract.rs
  packages/fuels-contract/src/script.rs
  packages/fuels-core/src/abi_decoder.rs
  packages/fuels-core/src/abi_encoder.rs
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/code_gen/bindings.rs
  packages/fuels-core/src/code_gen/custom_types_gen.rs
  packages/fuels-core/src/code_gen/functions_gen.rs
  packages/fuels-core/src/encoding_utils.rs
  packages/fuels-core/src/json_abi.rs
  packages/fuels-core/src/lib.rs
  packages/fuels-core/src/types.rs
  packages/fuels-signers/Cargo.toml
  packages/fuels-signers/src/lib.rs
  packages/fuels-signers/src/provider.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/Cargo.toml
  packages/fuels-test-helpers/src/script.rs
  packages/fuels-test-helpers/src/signers.rs
  packages/fuels-types/Cargo.toml
  packages/fuels-types/src/errors.rs
  packages/fuels-types/src/lib.rs
  packages/fuels/Cargo.toml
  packages/fuels/src/lib.rs
  packages/wasm-tests/Cargo.toml
Labels: tech-debt, breaking

#441 feat: add manual initial storage slots
  docs/src/getting-started/basics.md
  examples/contracts/src/lib.rs
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-abigen-macro/tests/test_projects/storage/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/storage/src/main.sw
  packages/fuels-contract/src/contract.rs
Labels: enhancement

#442 feat: add initial storage automatically
  .github/workflows/ci.yml
  docs/src/getting-started/basics.md
  examples/contracts/src/lib.rs
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-abigen-macro/tests/test_projects/contract_storage_test/Forc.toml
  packages/fuels-abigen-macro/tests/test_projects/contract_storage_test/src/main.sw
  packages/fuels-abigen-macro/tests/test_projects/foo_caller_contract/src/main.sw
  packages/fuels-abigen-macro/tests/test_projects/nested_enums/src/main.sw
  packages/fuels-abigen-macro/tests/test_projects/storage/src/main.sw
  packages/fuels-contract/src/contract.rs
  packages/fuels-core/src/parameters.rs
Labels: enhancement

#459 add check for invalid path
  packages/fuels-abigen-macro/tests/harness.rs
  packages/fuels-contract/src/contract.rs
Labels: enhancement

#457 refactor!: move `ParamType` type inside `fuels-types`
  packages/fuels-contract/src/contract.rs
  packages/fuels-core/src/abi_decoder.rs
  packages/fuels-core/src/abi_encoder.rs
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/encoding_utils.rs
  packages/fuels-core/src/json_abi.rs
  packages/fuels-core/src/lib.rs
  packages/fuels-types/src/lib.rs
  packages/fuels-types/src/param_types.rs
  packages/wasm-tests/src/lib.rs
  tools/fuels-abi-cli/src/main.rs
Labels: tech-debt, breaking

#468 docs: follow-ups from the book re-org
  docs/src/api/utils-and-helpers.md
  docs/src/testing/chains.md
  docs/src/testing/scripts.md
  docs/src/wallets/creating-a-wallet.md
  docs/src/wallets/test-wallets.md
  examples/providers/src/lib.rs
  examples/wallets/src/lib.rs
  packages/fuels-test-helpers/src/signers.rs
Labels: documentation

#472 docs: add section for custom types
  docs/src/SUMMARY.md
  docs/src/contracts/the-abigen-macro.md
  docs/src/types/custom_types.md
  packages/fuels-abigen-macro/tests/harness.rs
Labels: documentation

#458 Collision with rust bindings if Sway fn is called `new`
  examples/contracts/src/lib.rs
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels/tests/harness.rs
  packages/fuels/tests/test_projects/collision_in_fn_names/Forc.toml
  packages/fuels/tests/test_projects/collision_in_fn_names/src/main.sw
Labels: enhancement

#479 Set fuel-core stdin/stdout stream to null
  packages/fuels-test-helpers/src/node.rs
Labels: bug

#466 refactor: improve naming and documentation in `json_abi`
  packages/fuels-contract/src/script.rs
  packages/fuels-core/src/abi_decoder.rs
  packages/fuels-core/src/abi_encoder.rs
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/code_gen/custom_types_gen.rs
  packages/fuels-core/src/code_gen/functions_gen.rs
  packages/fuels-core/src/constants.rs
  packages/fuels-core/src/encoding_utils.rs
  packages/fuels-core/src/json_abi.rs
  packages/fuels-core/src/lib.rs
  packages/fuels-core/src/parse.rs
  packages/fuels-core/src/utils.rs
  packages/fuels-types/src/constants.rs
  packages/fuels-types/src/lib.rs
  packages/fuels-types/src/param_types.rs
  tools/fuels-abi-cli/src/main.rs
Labels: tech-debt

#482 feat: add gas used to call response
  docs/src/calling-contracts/call-response.md
  packages/fuels-contract/src/contract.rs
  packages/fuels/tests/harness.rs
Labels: enhancement

#419 feat!: add `transaction_parameters` to config json
  Cargo.toml
  packages/fuels-contract/Cargo.toml
  packages/fuels-contract/src/contract.rs
  packages/fuels-contract/src/script.rs
  packages/fuels-signers/src/lib.rs
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/node.rs
  packages/fuels-test-helpers/src/script.rs
  packages/fuels-test-helpers/src/signers.rs
  packages/fuels-types/src/errors.rs
  packages/fuels/Cargo.toml
  packages/fuels/tests/harness.rs
Labels: enhancement, breaking

#492 refactor: move function selector methods out of `ABIParser` struct
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/code_gen/custom_types_gen.rs
  packages/fuels-core/src/code_gen/functions_gen.rs
  packages/fuels-core/src/json_abi.rs
  packages/fuels-core/src/utils.rs
  packages/fuels-types/src/function_selector.rs
  packages/fuels-types/src/lib.rs
  packages/fuels-types/src/utils.rs
Labels: enhancement, tech-debt

#484 feat!: add multiple custom assets
  docs/src/wallets/test-wallets.md
  examples/wallets/src/lib.rs
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/signers.rs
  packages/fuels-test-helpers/src/wallets_config.rs
Labels: enhancement, breaking

#488 instantiating a fuel client bug
  examples/contracts/src/lib.rs
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/node.rs
  packages/fuels-types/src/errors.rs
  packages/fuels/src/lib.rs
Labels: enhancement

#467 feat: add bech32 support
  docs/src/types/bech32.md
  examples/contracts/src/lib.rs
  examples/providers/src/lib.rs
  examples/types/src/lib.rs
  examples/wallets/src/lib.rs
  packages/fuels-contract/src/contract.rs
  packages/fuels-contract/src/script.rs
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/code_gen/functions_gen.rs
  packages/fuels-signers/src/lib.rs
  packages/fuels-signers/src/provider.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/src/chains.rs
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/signers.rs
  packages/fuels-types/Cargo.toml
  packages/fuels-types/src/bech32.rs
  packages/fuels-types/src/errors.rs
  packages/fuels-types/src/lib.rs
  packages/fuels/src/lib.rs
  packages/fuels/tests/harness.rs
Labels: enhancement

#494 refactor: move tokenization methods inside a `Tokenizer` struct type
  packages/fuels-core/src/json_abi.rs
  packages/fuels-core/src/lib.rs
  packages/fuels-core/src/tokenizer.rs
Labels: tech-debt

#491 Add transfer to contract
  docs/src/SUMMARY.md
  docs/src/getting-started/managing-wallets.md
  docs/src/wallets/transferring-assets.md
  examples/wallets/src/lib.rs
  packages/fuels-contract/src/script.rs
  packages/fuels-signers/src/provider.rs
  packages/fuels-signers/src/wallet.rs
Labels: enhancement

#502 ci: use forc version 0.19.0
  .github/workflows/ci.yml
Labels: ci

#478 feat: refactor `produce_blocks` API
  docs/src/testing/chains.md
  packages/fuels-signers/src/provider.rs
  packages/fuels-test-helpers/src/chains.rs
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels/tests/harness.rs
Labels: tech-debt

#498 Improved error-handling
  examples/contracts/src/lib.rs
  examples/wallets/src/lib.rs
  packages/fuels-contract/src/contract.rs
  packages/fuels-contract/src/script.rs
  packages/fuels-core/src/code_gen/custom_types_gen.rs
  packages/fuels-core/src/code_gen/functions_gen.rs
  packages/fuels-core/src/json_abi.rs
  packages/fuels-signers/src/provider.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/src/script.rs
  packages/fuels-types/src/errors.rs
  packages/fuels/tests/harness.rs
Labels: enhancement
