Repository FuelLabs/fuels-rs, pull requests merged in 2022-09, with the labels that each got.

#554 docs: add build-test-projects and nocapture description
  docs/src/SUMMARY.md
  docs/src/getting-started/setup.md
Labels: documentation

#557 fix: Re-enable tests blocked by stdlib's gtf integration
  .github/workflows/ci.yml
  examples/contracts/src/lib.rs
  examples/cookbook/src/lib.rs
  packages/fuels/tests/harness.rs
  packages/fuels/tests/test_projects/predicate_address/src/main.sw
  packages/fuels/tests/test_projects/predicate_signatures/src/main.sw
  packages/fuels/tests/test_projects/predicate_struct/src/main.sw
  packages/fuels/tests/test_projects/predicate_u32/src/main.sw
Labels: P: critical

#559 Use flat abigen only and drop support for the old JSON ABI
  examples/rust_bindings/src/abi.json
  examples/rust_bindings/src/lib.rs
  packages/fuels-abigen-macro/src/lib.rs
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/code_gen/custom_types_gen.rs
  packages/fuels-core/src/code_gen/flat_abigen.rs
  packages/fuels-core/src/code_gen/functions_gen.rs
  packages/fuels-core/src/code_gen/mod.rs
  packages/fuels-core/src/json_abi.rs
  packages/fuels-core/src/tokenizer.rs
  packages/fuels-types/src/function_selector.rs
  packages/fuels-types/src/lib.rs
  packages/fuels-types/src/parse_param.rs
  packages/wasm-tests/src/lib.rs
  tools/fuels-abi-cli/src/main.rs
Labels: P: critical, breaking

#564 fix!: update connect method
  examples/providers/src/lib.rs
  packages/fuels-signers/src/provider.rs
  packages/fuels-test-helpers/src/script.rs
  packages/fuels/tests/harness.rs
Labels: breaking

#563 docs: add connect to testnet instructions
  docs/src/README.md
  docs/src/SUMMARY.md
  docs/src/getting-started/connecting.md
  docs/src/providers/external-node.md
  examples/providers/src/lib.rs
  packages/fuels/tests/harness.rs
Labels: documentation

#556 Use estimation to cover transaction fees
  docs/src/calling-contracts/cost-estimation.md
  docs/src/calling-contracts/tx-params.md
  docs/src/cookbook/transfer-all-assets.md
  examples/cookbook/src/lib.rs
  examples/predicates/src/lib.rs
  packages/fuels-contract/src/contract.rs
  packages/fuels-contract/src/script.rs
  packages/fuels-core/src/constants.rs
  packages/fuels-signers/src/provider.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels/tests/harness.rs
Labels: enhancement

#558 feat(test-helpers): warn if multiple `fuel-core` binaries are detected in `PATH`
  packages/fuels-test-helpers/Cargo.toml
  packages/fuels-test-helpers/src/node.rs
Labels: enhancement

#555 feat!: Add messages support
  examples/cookbook/src/lib.rs
  examples/predicates/src/lib.rs
  examples/providers/src/lib.rs
  examples/wallets/src/lib.rs
  packages/fuels-contract/Cargo.toml
  packages/fuels-contract/src/contract.rs
  packages/fuels-signers/Cargo.toml
  packages/fuels-signers/src/lib.rs
  packages/fuels-signers/src/provider.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/Cargo.toml
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/node.rs
  packages/fuels-test-helpers/src/signers.rs
  packages/fuels-types/Cargo.toml
  packages/fuels-types/src/lib.rs
  packages/fuels/Cargo.toml
  packages/fuels/tests/harness.rs
  scripts/check-docs/Cargo.toml
Labels: enhancement, breaking

#571 Make gas_forwarded use gas_limit as default
  docs/src/calling-contracts/call-params.md
  docs/src/calling-contracts/cost-estimation.md
  docs/src/calling-contracts/tx-params.md
  packages/fuels-contract/src/script.rs
  packages/fuels-core/src/constants.rs
  packages/fuels-core/src/parameters.rs
  packages/fuels/tests/harness.rs
Labels: enhancement

#578 refactor: expose the default derivation path to downstream crates
  packages/fuels-signers/src/wallet.rs
Labels: tech-debt

#574 feat: add options and results support
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/constants.rs
  packages/fuels-core/src/lib.rs
  packages/fuels-types/src/lib.rs
  packages/fuels/tests/harness.rs
  packages/fuels/tests/test_projects/options/Forc.toml
  packages/fuels/tests/test_projects/options/src/main.sw
  packages/fuels/tests/test_projects/results/Forc.toml
  packages/fuels/tests/test_projects/results/src/main.sw
Labels: enhancement, P: critical, package:abigen, package:core

#580 docs: update docs related to the changes introduced by generics
  docs/src/SUMMARY.md
  docs/src/types/bits256.md
  docs/src/types/bytes32.md
  docs/src/types/custom_types.md
  docs/src/types/string.md
  packages/fuels-core/src/types/sized_ascii_string.rs
  packages/fuels/tests/harness.rs
Labels: documentation

#587 refactor: fn_selector to be resolved during runtime via ParamTypes
  .github/workflows/ci.yml
  packages/fuels-core/src/abi_decoder.rs
  packages/fuels-core/src/abi_encoder.rs
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/code_gen/custom_types.rs
  packages/fuels-core/src/code_gen/custom_types/enum_gen.rs
  packages/fuels-core/src/code_gen/custom_types/struct_gen.rs
  packages/fuels-core/src/code_gen/custom_types/utils.rs
  packages/fuels-core/src/code_gen/function_selector.rs
  packages/fuels-core/src/code_gen/functions_gen.rs
  packages/fuels-core/src/code_gen/resolved_type.rs
  packages/fuels-core/src/json_abi.rs
  packages/fuels-core/src/lib.rs
  packages/fuels-core/src/tokenizer.rs
  packages/fuels-core/src/types.rs
  packages/fuels-core/src/types/array.rs
  packages/fuels-core/src/types/byte.rs
  packages/fuels-core/src/types/native.rs
  packages/fuels-types/src/lib.rs
  packages/fuels-types/src/param_types.rs
  packages/fuels-types/src/parse_param.rs
  packages/fuels/tests/harness.rs
  packages/fuels/tests/test_projects/revert_transaction_error/src/main.sw
  packages/wasm-tests/src/lib.rs
Labels: tech-debt

#592 refactor!: add methods() to contract abigen
  docs/src/calling-contracts/calls-with-different-wallets.md
  docs/src/contracts/the-setup-contract-test-macro.md
  docs/src/cookbook/deposit-and-withdraw.md
  examples/contracts/src/lib.rs
  examples/cookbook/src/lib.rs
  packages/fuels-abigen-macro/src/lib.rs
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels/tests/harness.rs
Labels: breaking

#601 feat: add Identity as native type
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/lib.rs
  packages/fuels-core/src/types/native.rs
  packages/fuels-core/src/utils.rs
  packages/fuels-types/src/lib.rs
  packages/fuels/src/lib.rs
  packages/fuels/tests/harness.rs
  packages/fuels/tests/test_projects/identity/Forc.toml
  packages/fuels/tests/test_projects/identity/src/main.sw
Labels: bug
