Repository FuelLabs/fuels-rs, pull requests merged in 2022-11, with the labels that each got.

#660 docs: add a pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#636 refactor(fuels-core): add tests for resolved_type
  packages/fuels-core/src/code_gen/resolved_type.rs
Labels: tech-debt

#672 fix: remove predicates config flag
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/node.rs
Labels: bug

#673 feat!: Accept chain config as argument for node setup test helpers
  examples/contracts/src/lib.rs
  examples/cookbook/src/lib.rs
  examples/predicates/src/lib.rs
  examples/providers/src/lib.rs
  examples/wallets/src/lib.rs
  packages/fuels-signers/src/lib.rs
  packages/fuels-signers/src/provider.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/node.rs
  packages/fuels-test-helpers/src/script.rs
  packages/fuels-test-helpers/src/signers.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/predicates.rs
  packages/fuels/tests/providers.rs
  packages/fuels/tests/wallets.rs
Labels: breaking, testing

#678 Remove note on `--generate-logged-types` in the Book
  docs/src/calling-contracts/logs.md
Labels: documentation

#685 feat: add format and clean to `test-projects`
  .github/workflows/ci.yml
  Cargo.toml
  docs/src/getting-started/setup.md
  packages/fuels/tests/contracts/auth_testing_abi/Forc.toml
  packages/fuels/tests/contracts/foo_contract_abi/Forc.toml
  packages/fuels/tests/contracts/large_return_data/Forc.toml
  packages/fuels/tests/contracts/library_test/Forc.toml
  packages/fuels/tests/contracts/liquidity_pool/Forc.toml
  packages/fuels/tests/contracts/msg_amount/Forc.toml
  packages/fuels/tests/contracts/multiple_read_calls/Forc.toml
  packages/fuels/tests/contracts/revert_transaction_error/Forc.toml
  packages/fuels/tests/contracts/token_ops/Forc.toml
  packages/fuels/tests/contracts/transaction_block_height/Forc.toml
  packages/fuels/tests/logs/logged_types/Forc.toml
  packages/fuels/tests/logs/logged_types/src/main.sw
  packages/fuels/tests/logs/logging/Forc.toml
  packages/fuels/tests/predicates/predicate_address/Forc.toml
  packages/fuels/tests/predicates/predicate_false/Forc.toml
  packages/fuels/tests/predicates/predicate_signatures/Forc.toml
  packages/fuels/tests/predicates/predicate_struct/Forc.toml
  packages/fuels/tests/predicates/predicate_true/Forc.toml
  packages/fuels/tests/predicates/predicate_u32/Forc.toml
  packages/fuels/tests/storage/contract_storage_test/Forc.toml
  packages/fuels/tests/types/call_empty_return/Forc.toml
  packages/fuels/tests/types/contract_output_test/Forc.toml
  packages/fuels/tests/types/empty_arguments/Forc.toml
  packages/fuels/tests/types/enum_as_input/Forc.toml
  packages/fuels/tests/types/enum_encoding/Forc.toml
  packages/fuels/tests/types/enum_inside_struct/Forc.toml
  packages/fuels/tests/types/generics/Forc.toml
  packages/fuels/tests/types/generics/src/main.sw
  packages/fuels/tests/types/identity/Forc.toml
  packages/fuels/tests/types/native_types/Forc.toml
  packages/fuels/tests/types/nested_structs/Forc.toml
  packages/fuels/tests/types/options/Forc.toml
  packages/fuels/tests/types/results/Forc.toml
  packages/fuels/tests/types/str_in_array/Forc.toml
  packages/fuels/tests/types/tuples/Forc.toml
  packages/fuels/tests/types/tuples/src/main.sw
  packages/fuels/tests/types/two_structs/Forc.toml
  packages/fuels/tests/types/type_inside_enum/Forc.toml
  packages/fuels/tests/types/vectors/Forc.toml
  packages/fuels/tests/types/vectors/src/main.sw
  scripts/build-test-projects/Cargo.toml
  scripts/build-test-projects/src/main.rs
  scripts/test-projects/Cargo.toml
  scripts/test-projects/src/cli.rs
  scripts/test-projects/src/lib.rs
  scripts/test-projects/src/main.rs
  scripts/test-projects/src/types.rs
Labels: testing

#668 feat: support evm address
  docs/src/SUMMARY.md
  docs/src/types/evm_address.md
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/types/bits_256.rs
  packages/fuels/tests/bindings.rs
  packages/fuels/tests/types.rs
  packages/fuels/tests/types/evm_address/Forc.toml
  packages/fuels/tests/types/evm_address/src/main.sw
Labels: enhancement

#628 Contract input set estimation
  .github/workflows/ci.yml
  packages/fuels-contract/src/contract.rs
  packages/fuels-contract/src/script.rs
  packages/fuels/tests/contracts.rs
Labels: enhancement

#697 chore: update `deploy_with_parameters` in docs
  docs/src/api/contracts.md
  docs/src/api/providers.md
  docs/src/api/wallets.md
  docs/src/getting-started/basics.md
  docs/src/getting-started/contracts.md
  docs/src/workspaces/fuels-abi-cli.md
  docs/src/workspaces/fuels-abigen-macro.md
  docs/src/workspaces/index.md
Labels: documentation

#684 feat: Add support for custom block time
  docs/src/testing/chains.md
  packages/fuels-signers/Cargo.toml
  packages/fuels-signers/src/provider.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-types/Cargo.toml
  packages/fuels-types/src/block.rs
  packages/fuels-types/src/lib.rs
  packages/fuels/Cargo.toml
  packages/fuels/tests/providers.rs
Labels: enhancement

#704 docs(fuels-{contract,core}): minor updates
  packages/fuels-contract/src/contract.rs
  packages/fuels-contract/src/contract_calls_utils.rs
  packages/fuels-contract/src/execution_script.rs
  packages/fuels-contract/src/script_calls.rs
  packages/fuels-core/src/abi_encoder.rs
  packages/fuels-core/src/code_gen/functions_gen.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-types/src/lib.rs
Labels: documentation

#705 docs: update forc setup and test workflow
  docs/src/getting-started/setup.md
Labels: documentation

#690 feat!: add parsed log to revert error
  docs/src/calling-contracts/call-response.md
  docs/src/calling-contracts/logs.md
  packages/fuels-abigen-macro/src/lib.rs
  packages/fuels-contract/Cargo.toml
  packages/fuels-contract/src/contract.rs
  packages/fuels-contract/src/lib.rs
  packages/fuels-contract/src/logs.rs
  packages/fuels-core/Cargo.toml
  packages/fuels-core/src/abi_decoder.rs
  packages/fuels-core/src/abi_encoder.rs
  packages/fuels-core/src/code_gen.rs
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/code_gen/custom_types.rs
  packages/fuels-core/src/code_gen/custom_types/enum_gen.rs
  packages/fuels-core/src/code_gen/custom_types/struct_gen.rs
  packages/fuels-core/src/code_gen/function_selector.rs
  packages/fuels-core/src/code_gen/functions_gen.rs
  packages/fuels-core/src/lib.rs
  packages/fuels-core/src/tokenizer.rs
  packages/fuels-core/src/types/bits.rs
  packages/fuels-core/src/types/native.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/Cargo.toml
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/node.rs
  packages/fuels-types/src/bech32.rs
  packages/fuels-types/src/enum_variants.rs
  packages/fuels-types/src/errors.rs
  packages/fuels-types/src/param_types.rs
  packages/fuels/Cargo.toml
  packages/fuels/src/lib.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/contracts/require/Forc.toml
  packages/fuels/tests/contracts/require/src/main.sw
  packages/fuels/tests/contracts/revert_transaction_error/src/main.sw
  packages/fuels/tests/logs.rs
  packages/fuels/tests/providers.rs
  packages/wasm-tests/src/lib.rs
Labels: breaking

#620 feat: support main function arguments in scripts
  docs/src/SUMMARY.md
  docs/src/calling-contracts/call-response.md
  docs/src/calling-contracts/logs.md
  docs/src/calling-contracts/multicalls.md
  docs/src/getting-started/running-scripts.md
  docs/src/scripts/scripts.md
  docs/src/testing/index.md
  examples/contracts/src/lib.rs
  examples/predicates/src/lib.rs
  packages/fuels-abigen-macro/src/lib.rs
  packages/fuels-contract/src/call_response.rs
  packages/fuels-contract/src/contract.rs
  packages/fuels-contract/src/contract_calls_utils.rs
  packages/fuels-contract/src/execution_script.rs
  packages/fuels-contract/src/lib.rs
  packages/fuels-contract/src/logs.rs
  packages/fuels-contract/src/script.rs
  packages/fuels-contract/src/script_calls.rs
  packages/fuels-core/src/abi_encoder.rs
  packages/fuels-core/src/code_gen/abigen.rs
  packages/fuels-core/src/code_gen/custom_types.rs
  packages/fuels-core/src/code_gen/functions_gen.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/script.rs
  packages/fuels-types/src/lib.rs
  packages/fuels/src/lib.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/scripts.rs
  packages/fuels/tests/scripts/basic_script/Forc.toml
  packages/fuels/tests/scripts/basic_script/src/main.sw
  packages/fuels/tests/scripts/script_generic_types/Forc.toml
  packages/fuels/tests/scripts/script_generic_types/src/main.sw
  packages/fuels/tests/scripts/script_option_result_types/Forc.toml
  packages/fuels/tests/scripts/script_option_result_types/src/main.sw
  packages/fuels/tests/scripts/script_tuple_argument/Forc.toml
  packages/fuels/tests/scripts/script_tuple_argument/src/main.sw
  packages/fuels/tests/scripts/script_tuple_types/Forc.toml
  packages/fuels/tests/scripts/script_tuple_types/src/main.sw
  packages/fuels/tests/scripts/script_with_arguments/Forc.toml
  packages/fuels/tests/scripts/script_with_arguments/src/main.sw
Labels: breaking

#715 fix: pay tx fees with message
  packages/fuels-signers/src/wallet.rs
  packages/fuels/tests/providers.rs
Labels: bug
