Repository FuelLabs/fuels-rs, pull requests merged in 2023-06, with the labels that each got.

#987 refactor: path of `WalletUnlocked` in `fuels::accounts`
  examples/contracts/src/lib.rs
  examples/cookbook/src/lib.rs
  examples/predicates/src/lib.rs
  examples/providers/src/lib.rs
  examples/wallets/src/lib.rs
  packages/fuels-accounts/src/lib.rs
  packages/fuels-core/src/codec/abi_decoder.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-test-helpers/src/accounts.rs
  packages/fuels/src/lib.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/predicates.rs
  packages/fuels/tests/providers.rs
  packages/fuels/tests/scripts.rs
  packages/fuels/tests/types_predicates.rs
  packages/fuels/tests/wallets.rs
Labels: bug

#993 fix: create message type based on data length
  packages/fuels-core/src/types/transaction_builders.rs
Labels: bug

#1004 refactor: remove setter from account trait
  packages/fuels-accounts/src/lib.rs
  packages/fuels-accounts/src/predicate.rs
  packages/fuels-accounts/src/wallet.rs
Labels: enhancement

#1003 chore: update sign_and_verify test
  packages/fuels-accounts/src/lib.rs
  packages/fuels-core/src/types/wrappers/coin.rs
Labels: documentation, testing

#1010 docs: match folders with navigation
  docs/src/SUMMARY.md
  docs/src/abigen/index.md
  docs/src/accounts.md
  docs/src/calling-contracts/call-params.md
  docs/src/calling-contracts/index.md
  docs/src/calling-contracts/tx-dependency-estimation.md
  docs/src/connecting/external-node.md
  docs/src/connecting/index.md
  docs/src/connecting/querying.md
  docs/src/connecting/short-lived.md
  docs/src/cookbook/index.md
  docs/src/debugging/abigen.md
  docs/src/debugging/contract-calls.md
  docs/src/debugging/index.md
  docs/src/debugging/network.md
  docs/src/deploying/configurable-constants.md
  docs/src/deploying/index.md
  docs/src/deploying/interacting-with-contracts.md
  docs/src/deploying/the-fuelvm-binary-file.md
  docs/src/getting-started.md
  docs/src/getting-started/index.md
  docs/src/glossary.md
  docs/src/predicates/index.md
  docs/src/predicates/send-spend-predicate.md
  docs/src/reference.md
  docs/src/running-scripts.md
  docs/src/wallets/index.md
Labels: documentation

#976 feat!: add output variable estimation for `ScriptCallHandler`
  docs/src/calling-contracts/tx-dependency-estimation.md
  examples/contracts/src/lib.rs
  packages/fuels-core/src/types/wrappers/input.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/script_calls.rs
  packages/fuels/Forc.toml
  packages/fuels/src/lib.rs
  packages/fuels/tests/scripts.rs
  packages/fuels/tests/scripts/transfer_script/Forc.toml
  packages/fuels/tests/scripts/transfer_script/src/main.sw
Labels: enhancement

#1016 ci: use nextest
  .github/workflows/ci.yml
Labels: ci

#1021 feat: add `WalletUnlocked` to `prelude`
  examples/contracts/src/lib.rs
  examples/cookbook/src/lib.rs
  examples/predicates/src/lib.rs
  examples/providers/src/lib.rs
  examples/wallets/src/lib.rs
  packages/fuels/src/lib.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/predicates.rs
  packages/fuels/tests/providers.rs
  packages/fuels/tests/scripts.rs
  packages/fuels/tests/types_predicates.rs
Labels: enhancement

#1024 ci: add back doctest testing
  .github/workflows/ci.yml
Labels: ci
