Repository FuelLabs/fuels-rs, pull requests merged in 2023-05, with the labels that each got.

#957 chore: bump `syn` to `2.0`
  Cargo.toml
  packages/fuels-macros/src/derive/utils.rs
  packages/fuels-macros/src/lib.rs
  packages/fuels-macros/src/parse_utils.rs
  packages/fuels-macros/src/parse_utils/command.rs
  packages/fuels-macros/src/parse_utils/unique_lit_strs.rs
  packages/fuels-macros/src/parse_utils/unique_name_values.rs
  packages/fuels-macros/src/setup_program_test/parsing/commands/abigen.rs
  packages/fuels-macros/src/utils.rs
  packages/fuels-macros/tests/ui/derive/parameterize/attribute_must_be_named_value.rs
  packages/fuels-macros/tests/ui/derive/parameterize/attribute_must_be_named_value.stderr
  packages/fuels-macros/tests/ui/derive/tokenizable/attribute_must_be_named_value.stderr
  packages/fuels-types/src/core/bits.rs
  packages/fuels-types/src/core/native.rs
Labels: tech-debt

#963 chore: default-features warnings on cargo nightly
  Cargo.toml
  packages/fuels-macros/src/setup_program_test/code_gen.rs
Labels: tech-debt

#961 bug: reexport lost fuels::tx::Output under fuels::types::output::Output
  packages/fuels-types/src/lib.rs
Labels: bug

#972 feat!: add `u128` support
  packages/fuels-code-gen/src/program_bindings/utils.rs
  packages/fuels-core/src/abi_decoder.rs
  packages/fuels-core/src/abi_encoder.rs
  packages/fuels-core/src/function_selector.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-types/src/core.rs
  packages/fuels-types/src/param_types.rs
  packages/fuels-types/src/traits/parameterize.rs
  packages/fuels-types/src/traits/tokenizable.rs
  packages/fuels/Forc.toml
  packages/fuels/tests/predicates.rs
  packages/fuels/tests/types/contracts/u128/Forc.toml
  packages/fuels/tests/types/contracts/u128/src/main.sw
  packages/fuels/tests/types/predicates/predicate_u128/Forc.toml
  packages/fuels/tests/types/predicates/predicate_u128/src/main.sw
  packages/fuels/tests/types/scripts/script_u128/Forc.toml
  packages/fuels/tests/types/scripts/script_u128/src/main.sw
  packages/fuels/tests/types_contracts.rs
  packages/fuels/tests/types_predicates.rs
  packages/fuels/tests/types_scripts.rs
Labels: enhancement

#973 feat: add gas estimation to script calls
  packages/fuels-programs/src/script_calls.rs
  packages/fuels/tests/scripts.rs
Labels: enhancement

#734 feat(contracts): add tx_id to FuelCallResponse
  docs/src/calling-contracts/call-response.md
  packages/fuels-programs/src/call_response.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/script_calls.rs
  packages/fuels/tests/scripts.rs
Labels: package:contracts

#958 feat: `low level call`support
  docs/src/SUMMARY.md
  docs/src/calling-contracts/low-level-calls.md
  examples/contracts/src/lib.rs
  examples/debugging/src/lib.rs
  packages/fuels-core/src/function_selector.rs
  packages/fuels/Forc.toml
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/contracts/contract_test/src/main.sw
  packages/fuels/tests/contracts/low_level_caller/Forc.toml
  packages/fuels/tests/contracts/low_level_caller/src/main.sw
Labels: enhancement
