Repository FuelLabs/fuels-rs, pull requests merged in 2023-01, with the labels that each got.

#760 Remove empty doc section on scripts
  docs/src/SUMMARY.md
  docs/src/scripts/index.md
  docs/src/scripts/scripts.md
Labels: documentation

#756 Add estimate tx dependencies to docs
  docs/src/SUMMARY.md
  docs/src/calling-contracts/tx-dependency-estimation.md
  docs/src/calling-contracts/variable-outputs.md
  examples/contracts/src/lib.rs
  packages/fuels/tests/contracts/foo_caller_contract/src/main.sw
  packages/fuels/tests/contracts/token_ops/src/main.sw
Labels: documentation

#777 fix: do not modify receipts
  packages/fuels-contract/src/contract.rs
  packages/fuels-contract/src/script_calls.rs
Labels: bug

#784 style!: use C-style getters naming for SDK methods
  examples/rust_bindings/src/rust_bindings_formatted.rs
  packages/fuels-abigen-macro/.gitignore
  packages/fuels-core/src/code_gen/abigen/bindings/contract.rs
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/node.rs
  packages/fuels-test-helpers/src/utils.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/providers.rs
Labels: breaking

#805 Reorganize navigation, add testing basics page
  README.md
  docs/src/SUMMARY.md
  docs/src/debugging/debugging.md
  docs/src/getting-started/api.md
  docs/src/testing/basics.md
  docs/src/testing/index.md
  docs/src/types/index.md
Labels: documentation
