Repository FuelLabs/fuels-rs, pull requests merged in 2023-04, with the labels that each got.

#921 chore: default-features warnings on cargo nightly
  Cargo.toml
  packages/fuels-accounts/Cargo.toml
  packages/fuels-core/Cargo.toml
  packages/fuels-programs/Cargo.toml
  packages/fuels-test-helpers/Cargo.toml
  packages/fuels-types/Cargo.toml
  packages/fuels/Cargo.toml
Labels: tech-debt

#904 feat: add support for `Bytes` and `RawSlice` inputs
  packages/fuels-core/src/abi_encoder.rs
  packages/fuels-core/src/function_selector.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-types/src/param_types.rs
  packages/fuels/Forc.toml
  packages/fuels/src/lib.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/types/contracts/bytes/src/main.sw
  packages/fuels/tests/types/contracts/raw_slice/src/main.sw
  packages/fuels/tests/types/predicates/predicate_bytes/Forc.toml
  packages/fuels/tests/types/predicates/predicate_bytes/src/main.sw
  packages/fuels/tests/types/predicates/predicate_raw_slice/Forc.toml
  packages/fuels/tests/types/predicates/predicate_raw_slice/src/main.sw
  packages/fuels/tests/types/scripts/script_bytes/Forc.toml
  packages/fuels/tests/types/scripts/script_bytes/src/main.sw
  packages/fuels/tests/types/scripts/script_raw_slice/src/main.sw
  packages/fuels/tests/types_contracts.rs
  packages/fuels/tests/types_predicates.rs
  packages/fuels/tests/types_scripts.rs
Labels: enhancement

#899 refactor!: separate `Contract` loading and deploying
  docs/src/getting-started/contracts.md
  examples/contracts/src/lib.rs
  examples/cookbook/src/lib.rs
  examples/wallets/src/lib.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/contract.rs
  packages/fuels-macros/src/setup_contract_test/code_gen.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-types/src/transaction_builders.rs
  packages/fuels/src/lib.rs
  packages/fuels/tests/configurables.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/logs.rs
  packages/fuels/tests/predicates.rs
  packages/fuels/tests/providers.rs
  packages/fuels/tests/storage.rs
  packages/fuels/tests/types_contracts.rs
Labels: tech-debt

#919 feat!: add `LogResult` struct
  docs/src/calling-contracts/logs.md
  docs/src/getting-started/running-scripts.md
  packages/fuels-programs/src/call_response.rs
  packages/fuels-programs/src/logs.rs
  packages/fuels/tests/logs.rs
  packages/fuels/tests/logs/contract_logs/src/main.sw
  packages/fuels/tests/logs/contract_logs_abi/src/main.sw
Labels: breaking

#910 feat!: support scripts and predicates in `setup_program_test!` (old `setup_contract_test`)
  docs/src/SUMMARY.md
  docs/src/testing/index.md
  docs/src/testing/the-setup-program-test-macro.md
  examples/contracts/src/lib.rs
  packages/fuels-code-gen/src/program_bindings/abigen/abigen_target.rs
  packages/fuels-macros/src/abigen/parsing.rs
  packages/fuels-macros/src/lib.rs
  packages/fuels-macros/src/setup_contract_test.rs
  packages/fuels-macros/src/setup_contract_test/parsing.rs
  packages/fuels-macros/src/setup_program_test.rs
  packages/fuels-macros/src/setup_program_test/code_gen.rs
  packages/fuels-macros/src/setup_program_test/parsing.rs
  packages/fuels-macros/src/setup_program_test/parsing/command_parser.rs
  packages/fuels-macros/src/setup_program_test/parsing/commands.rs
  packages/fuels-macros/src/setup_program_test/parsing/commands/abigen.rs
  packages/fuels-macros/src/setup_program_test/parsing/commands/deploy_contract.rs
  packages/fuels-macros/src/setup_program_test/parsing/commands/initialize_wallet.rs
  packages/fuels-macros/src/setup_program_test/parsing/commands/load_script.rs
  packages/fuels-macros/src/setup_program_test/parsing/validations.rs
  packages/fuels-macros/tests/macro_usage.rs
  packages/fuels-macros/tests/ui/abigen/invalid_program_type.stderr
  packages/fuels-macros/tests/ui/setup_contract_test/contract_not_generated.stderr
  packages/fuels-macros/tests/ui/setup_contract_test/duplicate_wallet_command.rs
  packages/fuels-macros/tests/ui/setup_contract_test/duplicate_wallet_names.rs
  packages/fuels-macros/tests/ui/setup_program_test/abigen_command_is_missing.rs
  packages/fuels-macros/tests/ui/setup_program_test/abigen_command_is_missing.stderr
  packages/fuels-macros/tests/ui/setup_program_test/duplicate_wallet_command.rs
  packages/fuels-macros/tests/ui/setup_program_test/duplicate_wallet_command.stderr
  packages/fuels-macros/tests/ui/setup_program_test/duplicate_wallet_names.rs
  packages/fuels-macros/tests/ui/setup_program_test/duplicate_wallet_names.stderr
  packages/fuels-macros/tests/ui/setup_program_test/unknown_command.rs
  packages/fuels-macros/tests/ui/setup_program_test/unknown_command.stderr
  packages/fuels-macros/tests/ui/setup_program_test/unknown_contract.rs
  packages/fuels-macros/tests/ui/setup_program_test/unknown_contract.stderr
  packages/fuels/src/lib.rs
  packages/fuels/tests/bindings.rs
  packages/fuels/tests/configurables.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/logs.rs
  packages/fuels/tests/providers.rs
  packages/fuels/tests/scripts.rs
  packages/fuels/tests/types_contracts.rs
  packages/fuels/tests/types_scripts.rs
Labels: enhancement, tech-debt, breaking

#916 feat: add receipt decoder
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/lib.rs
  packages/fuels-programs/src/receipt_parser.rs
  packages/fuels-programs/src/script_calls.rs
  packages/fuels/tests/contracts.rs
Labels: bug, enhancement, breaking

#937 feat: expose code root
  packages/fuels-programs/src/contract.rs
Labels: enhancement

#935 feat!: add predicate configurables
  docs/src/contracts/configurable-constants.md
  docs/src/getting-started/predicates.md
  docs/src/getting-started/running-scripts.md
  docs/src/testing/the-setup-program-test-macro.md
  examples/predicates/src/lib.rs
  packages/fuels-accounts/src/predicate.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/predicate.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/script.rs
  packages/fuels-code-gen/src/program_bindings/abigen/configurables.rs
  packages/fuels-core/src/lib.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/lib.rs
  packages/fuels/Forc.toml
  packages/fuels/src/lib.rs
  packages/fuels/tests/predicates.rs
  packages/fuels/tests/predicates/predicate_configurables/Forc.toml
  packages/fuels/tests/predicates/predicate_configurables/src/main.sw
  packages/fuels/tests/types_predicates.rs
Labels: enhancement

#941 Add predicate code getter
  packages/fuels-accounts/src/predicate.rs
Labels: enhancement
