Repository FuelLabs/fuels-rs, pull requests merged in 2023-11, with the labels that each got.

#1182 feat: generate full predicate abigen code in wasm
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/predicate.rs
  packages/wasm-tests/src/lib.rs
Labels: enhancement

#1185 fix: enum discriminant overflow
  packages/fuels-macros/src/derive/utils.rs
  packages/fuels-macros/tests/ui/derive/tokenizable/enum_size_not_supported.rs
  packages/fuels-macros/tests/ui/derive/tokenizable/enum_size_not_supported.stderr
  packages/fuels/tests/types/contracts/enum_as_input/src/main.sw
  packages/fuels/tests/types_contracts.rs
Labels: bug

#1105 feat: caching of recently used coins
  .github/workflows/ci.yml
  packages/fuels-accounts/Cargo.toml
  packages/fuels-accounts/src/account.rs
  packages/fuels-accounts/src/accounts_utils.rs
  packages/fuels-accounts/src/coin_cache.rs
  packages/fuels-accounts/src/lib.rs
  packages/fuels-accounts/src/predicate.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-accounts/src/wallet.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-core/src/types/wrappers.rs
  packages/fuels-core/src/types/wrappers/coin_type.rs
  packages/fuels-core/src/types/wrappers/coin_type_id.rs
  packages/fuels-core/src/types/wrappers/transaction.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/script_calls.rs
  packages/fuels-test-helpers/src/accounts.rs
  packages/fuels/Cargo.toml
  packages/fuels/tests/predicates.rs
  packages/fuels/tests/providers.rs
  packages/fuels/tests/wallets.rs
Labels: enhancement

#1163 feat!: represent small values as single bytes
  .github/workflows/ci.yml
  examples/contracts/src/lib.rs
  packages/fuels-accounts/src/accounts_utils.rs
  packages/fuels-accounts/src/provider/retry_util.rs
  packages/fuels-accounts/src/provider/retryable_client.rs
  packages/fuels-core/src/codec/abi_decoder.rs
  packages/fuels-core/src/codec/abi_decoder/bounded_decoder.rs
  packages/fuels-core/src/codec/abi_encoder.rs
  packages/fuels-core/src/codec/logs.rs
  packages/fuels-core/src/traits/tokenizable.rs
  packages/fuels-core/src/types.rs
  packages/fuels-core/src/types/core/bits.rs
  packages/fuels-core/src/types/core/u256.rs
  packages/fuels-core/src/types/enum_variants.rs
  packages/fuels-core/src/types/errors.rs
  packages/fuels-core/src/types/param_types.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-core/src/types/unresolved_bytes.rs
  packages/fuels-core/src/utils.rs
  packages/fuels-core/src/utils/constants.rs
  packages/fuels-macros/src/derive/utils.rs
  packages/fuels-macros/tests/ui/derive/tokenizable/enum_size_not_supported.rs
  packages/fuels-macros/tests/ui/derive/tokenizable/enum_size_not_supported.stderr
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-programs/src/receipt_parser.rs
  packages/fuels-test-helpers/src/service.rs
  packages/fuels/tests/bindings.rs
  packages/fuels/tests/bindings/sharing_types/contract_a/src/main.sw
  packages/fuels/tests/bindings/sharing_types/contract_b/src/main.sw
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/contracts/lib_contract_caller/src/main.sw
  packages/fuels/tests/contracts/liquidity_pool/src/main.sw
  packages/fuels/tests/contracts/low_level_caller/src/main.sw
  packages/fuels/tests/contracts/revert_transaction_error/src/main.sw
  packages/fuels/tests/from_token.rs
  packages/fuels/tests/providers.rs
  packages/fuels/tests/types/contracts/bytes/src/main.sw
  packages/fuels/tests/types/contracts/evm_address/src/main.sw
  packages/fuels/tests/types/contracts/generics/src/main.sw
  packages/fuels/tests/types/contracts/heap_type_in_enums/src/main.sw
  packages/fuels/tests/types/contracts/raw_slice/src/main.sw
  packages/fuels/tests/types/contracts/tuples/src/main.sw
  packages/fuels/tests/types/contracts/u128/src/main.sw
  packages/fuels/tests/types/contracts/u256/src/main.sw
  packages/fuels/tests/types/contracts/vector_output/src/main.sw
  packages/fuels/tests/types/predicates/address/src/main.sw
  packages/fuels/tests/types/predicates/predicate_tuples/src/main.sw
  packages/fuels/tests/types/predicates/predicate_u256/src/main.sw
  packages/fuels/tests/types/predicates/predicate_vectors/src/main.sw
  packages/fuels/tests/types/scripts/script_bytes/src/main.sw
  packages/fuels/tests/types/scripts/script_raw_slice/src/main.sw
  packages/fuels/tests/types/scripts/script_u256/src/main.sw
  packages/fuels/tests/types/scripts/script_vectors/src/main.sw
  packages/fuels/tests/types_contracts.rs
Labels: P: high, sway-compiler

#1200 feat!: `beta-5` support
  .github/workflows/ci.yml
  Cargo.toml
  docs/src/SUMMARY.md
  docs/src/accounts.md
  docs/src/calling-contracts/index.md
  docs/src/calling-contracts/multicalls.md
  docs/src/calling-contracts/tx-params.md
  docs/src/calling-contracts/tx-policies.md
  docs/src/running-scripts.md
  examples/contracts/src/lib.rs
  examples/cookbook/src/lib.rs
  examples/predicates/src/lib.rs
  examples/providers/src/lib.rs
  examples/wallets/src/lib.rs
  packages/fuels-accounts/src/account.rs
  packages/fuels-accounts/src/accounts_utils.rs
  packages/fuels-accounts/src/coin_cache.rs
  packages/fuels-accounts/src/predicate.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-accounts/src/provider/retryable_client.rs
  packages/fuels-accounts/src/provider/supported_versions.rs
  packages/fuels-core/Cargo.toml
  packages/fuels-core/src/codec/logs.rs
  packages/fuels-core/src/types/errors.rs
  packages/fuels-core/src/types/param_types.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-core/src/types/wrappers/chain_info.rs
  packages/fuels-core/src/types/wrappers/coin_type.rs
  packages/fuels-core/src/types/wrappers/transaction.rs
  packages/fuels-core/src/types/wrappers/transaction_response.rs
  packages/fuels-core/src/utils/constants.rs
  packages/fuels-core/src/utils/offsets.rs
  packages/fuels-macros/src/setup_program_test/code_gen.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/script_calls.rs
  packages/fuels-test-helpers/Cargo.toml
  packages/fuels-test-helpers/src/accounts.rs
  packages/fuels-test-helpers/src/fuel_bin_service.rs
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/node_types.rs
  packages/fuels/Forc.toml
  packages/fuels/src/lib.rs
  packages/fuels/tests/configurables.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/contracts/revert_transaction_error/src/main.sw
  packages/fuels/tests/logs.rs
  packages/fuels/tests/predicates.rs
  packages/fuels/tests/providers.rs
  packages/fuels/tests/scripts.rs
  packages/fuels/tests/storage.rs
  packages/fuels/tests/types/contracts/vector_output/src/main.sw
  packages/fuels/tests/types/scripts/script_vectors/src/main.sw
  packages/fuels/tests/types_contracts.rs
  packages/fuels/tests/types_predicates.rs
  packages/fuels/tests/types_scripts.rs
  packages/fuels/tests/wallets.rs
  packages/wasm-tests/src/lib.rs
Labels: big, breaking

#1205 feat: add `from_hex_str` for `Bytes`
  docs/src/SUMMARY.md
  docs/src/types/bytes.md
  packages/fuels-core/src/types/core/bytes.rs
  packages/fuels/Forc.toml
  packages/fuels/tests/types/predicates/predicate_bytes_hash/Forc.toml
  packages/fuels/tests/types/predicates/predicate_bytes_hash/src/main.sw
  packages/fuels/tests/types_contracts.rs
  packages/fuels/tests/types_predicates.rs
Labels: enhancement

#1203 bug: cannot fetch mint transactions
  packages/fuels-code-gen/src/program_bindings/utils.rs
  packages/fuels-core/src/codec/logs.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-core/src/types/wrappers/coin_type.rs
  packages/fuels-core/src/types/wrappers/transaction.rs
  packages/fuels-core/src/types/wrappers/transaction_response.rs
  packages/fuels/tests/providers.rs
Labels: bug

#1212 feat!: improve transaction builders wrt `TxPolicies`
  docs/src/calling-contracts/tx-policies.md
  packages/fuels-accounts/src/account.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-core/src/types/wrappers/transaction.rs
  packages/fuels-core/src/utils.rs
  packages/fuels-core/src/utils/constants.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/logs.rs
  packages/fuels/tests/predicates.rs
  packages/fuels/tests/providers.rs
  packages/fuels/tests/types_contracts.rs
  packages/fuels/tests/wallets.rs
Labels: enhancement

#1220 feat: get `TransactionBuilder` from script and contract calls
  docs/src/SUMMARY.md
  docs/src/custom-transactions/custom-calls.md
  docs/src/custom-transactions/index.md
  docs/src/custom-transactions/transaction-builders.md
  examples/contracts/src/lib.rs
  examples/cookbook/src/lib.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/script_calls.rs
  packages/fuels/Forc.toml
  packages/fuels/src/lib.rs
  packages/fuels/tests/predicates/swap/Forc.toml
  packages/fuels/tests/predicates/swap/src/main.sw
  packages/fuels/tests/scripts.rs
Labels: documentation, enhancement

#1217 feat!: deprecate `U256` and use `u256`
  packages/fuels-code-gen/src/program_bindings/resolved_type.rs
  packages/fuels-code-gen/src/program_bindings/utils.rs
  packages/fuels-core/src/codec/function_selector.rs
  packages/fuels/tests/types/contracts/u256/src/main.sw
  packages/fuels/tests/types/predicates/predicate_u256/src/main.sw
  packages/fuels/tests/types/scripts/script_u256/src/main.sw
  packages/fuels/tests/types_contracts.rs
Labels: enhancement, breaking
