Repository FuelLabs/fuels-rs, pull requests merged in 2023-02, with the labels that each got.

#806 fix: sign transaction in `ScriptCallHandler`
  packages/fuels-programs/src/script_calls.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/scripts.rs
Labels: bug

#827 Update for `fuel-asm` refactor. Updates for fuel-core 0.17, fuel-vm 0.26.
  .github/workflows/ci.yml
  Cargo.toml
  packages/fuels-core/src/offsets.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-types/src/message.rs
Labels: tech-debt, P: high

#811 feat: add support for assert_eq logs
  examples/contracts/src/lib.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/contract.rs
  packages/fuels-code-gen/src/program_bindings/abigen/logs.rs
  packages/fuels-core/src/utils.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/execution_script.rs
  packages/fuels-programs/src/logs.rs
  packages/fuels-signers/src/provider.rs
  packages/fuels-test-helpers/src/node.rs
  packages/fuels-types/src/errors.rs
  packages/fuels/src/lib.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/contracts/assert_eq/Forc.toml
  packages/fuels/tests/contracts/assert_eq/src/main.sw
  packages/fuels/tests/logs.rs
  packages/fuels/tests/providers.rs
  packages/fuels/tests/scripts/script_assert_eq/Forc.toml
  packages/fuels/tests/scripts/script_assert_eq/src/main.sw
Labels: blocked

#825 fix wasm compatibility when `no_std` is used in Abigen
  ci_checks.sh
  packages/fuels-code-gen/src/program_bindings/abigen.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/contract.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/predicate.rs
  packages/fuels-code-gen/src/program_bindings/abigen/logs.rs
  packages/fuels-code-gen/src/program_bindings/custom_types.rs
  packages/fuels-code-gen/src/program_bindings/custom_types/enums.rs
  packages/fuels-code-gen/src/program_bindings/custom_types/structs.rs
  packages/fuels-code-gen/src/program_bindings/resolved_type.rs
  packages/fuels-code-gen/src/program_bindings/utils.rs
  packages/fuels-macros/src/derive/parameterize.rs
  packages/fuels-macros/src/derive/tokenizable.rs
  packages/fuels-macros/src/derive/try_from.rs
  packages/fuels-macros/src/derive/utils.rs
  packages/fuels-macros/src/lib.rs
  packages/wasm-tests/Cargo.toml
  packages/wasm-tests/src/lib.rs
Labels: bug

#843 fix: clear environment before running fuel-core binary
  packages/fuels-test-helpers/src/node.rs
  packages/fuels/tests/providers.rs
Labels: bug

#801 Improve devx for extracting data from Script
  docs/src/calling-contracts/call-params.md
  docs/src/calling-contracts/tx-params.md
  examples/cookbook/src/lib.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/predicate.rs
  packages/fuels-core/src/constants.rs
  packages/fuels-core/src/lib.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/execution_script.rs
  packages/fuels-programs/src/lib.rs
  packages/fuels-programs/src/script_calls.rs
  packages/fuels-signers/src/lib.rs
  packages/fuels-signers/src/provider.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/signers.rs
  packages/fuels-types/Cargo.toml
  packages/fuels-types/src/constants.rs
  packages/fuels-types/src/lib.rs
  packages/fuels-types/src/parameters.rs
  packages/fuels-types/src/transaction.rs
  packages/fuels/src/lib.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/scripts.rs
Labels: enhancement, breaking

#838 docs: update the repo README
  README.md
Labels: documentation

#852 fix: ci individual package testing
  .github/workflows/ci.yml
  packages/fuels-signers/src/provider.rs
  packages/fuels-types/src/transaction.rs
Labels: bug

#839 fix!: wasm compatibility for `fuels-types`
  .github/workflows/ci.yml
  Cargo.toml
  README.md
  packages/fuels-code-gen/src/program_bindings.rs
  packages/fuels-code-gen/src/program_bindings/abigen/abigen_target.rs
  packages/fuels-code-gen/src/utils.rs
  packages/fuels-code-gen/src/utils/source.rs
  packages/fuels-core/Cargo.toml
  packages/fuels-programs/Cargo.toml
  packages/fuels-signers/Cargo.toml
  packages/fuels-test-helpers/Cargo.toml
  packages/fuels-types/Cargo.toml
  packages/fuels-types/src/block.rs
  packages/fuels-types/src/chain_info.rs
  packages/fuels-types/src/coin.rs
  packages/fuels-types/src/message.rs
  packages/fuels-types/src/message_proof.rs
  packages/fuels-types/src/node_info.rs
  packages/fuels-types/src/resource.rs
  packages/fuels-types/src/transaction_response.rs
  packages/fuels/Cargo.toml
  packages/wasm-tests/.cargo/config.toml
  packages/wasm-tests/Cargo.toml
  packages/wasm-tests/src/lib.rs
Labels: bug

#857 fix: latest release cannot be used by cargo
  packages/fuels-core/Cargo.toml
  packages/fuels-programs/Cargo.toml
  packages/fuels-signers/Cargo.toml
Labels: bug

#846 Add message output estimation
  packages/fuels-programs/src/contract.rs
  packages/fuels/tests/contracts.rs
Labels: enhancement
