Repository FuelLabs/fuels-rs, pull requests merged in 2023-10, with the labels that each got.

#1142 refactor: use `TxStatus` to map revert errors
  packages/fuels-accounts/src/provider.rs
  packages/fuels-core/src/codec/logs.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/script_calls.rs
  packages/fuels/tests/providers.rs
Labels: tech-debt

#1145 feat: check deploy tx status
  packages/fuels-accounts/src/provider.rs
  packages/fuels-core/src/types/errors.rs
  packages/fuels-core/src/types/tx_status.rs
  packages/fuels-programs/src/contract.rs
Labels: tech-debt

#1098 chore(docs): use variables for docs.rs links
  .github/workflows/docs.yml
  Cargo.toml
  docs/src/calling-contracts/call-params.md
  docs/src/connecting/querying.md
  docs/src/getting-started.md
  docs/src/reference.md
  docs/src/types/address.md
  docs/src/types/asset-id.md
  docs/src/types/bytes32.md
  docs/src/types/contract-id.md
  scripts/versions-replacer/Cargo.toml
  scripts/versions-replacer/src/lib.rs
  scripts/versions-replacer/src/main.rs
  scripts/versions-replacer/src/metadata.rs
  scripts/versions-replacer/src/replace.rs
Labels: documentation, tech-debt

#1106 feat: return Enums containing heap types at depth 1
  packages/fuels-core/src/codec/abi_decoder.rs
  packages/fuels-core/src/codec/abi_decoder/bounded_decoder.rs
  packages/fuels-core/src/types/enum_variants.rs
  packages/fuels-core/src/types/param_types.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/receipt_parser.rs
  packages/fuels/Forc.toml
  packages/fuels/tests/types/contracts/heap_type_in_enums/Forc.toml
  packages/fuels/tests/types/contracts/heap_type_in_enums/src/main.sw
  packages/fuels/tests/types_contracts.rs
Labels: enhancement, package:core

#1148 feat: bump `forc` to `0.46.0`
  .github/workflows/ci.yml
  Cargo.toml
  docs/src/calling-contracts/logs.md
  examples/contracts/src/lib.rs
  packages/fuels-code-gen/src/program_bindings/utils.rs
  packages/fuels-core/src/codec/logs.rs
  packages/fuels/Forc.toml
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/contracts/configurables/src/main.sw
  packages/fuels/tests/contracts/contract_test/src/main.sw
  packages/fuels/tests/contracts/large_return_data/src/main.sw
  packages/fuels/tests/contracts/lib_contract/src/main.sw
  packages/fuels/tests/contracts/liquidity_pool/src/main.sw
  packages/fuels/tests/contracts/require/src/main.sw
  packages/fuels/tests/logs.rs
  packages/fuels/tests/logs/contract_logs/src/main.sw
  packages/fuels/tests/logs/contract_logs_abi/src/main.sw
  packages/fuels/tests/logs/script_logs/src/main.sw
  packages/fuels/tests/logs/script_with_contract_logs/src/main.sw
  packages/fuels/tests/providers.rs
  packages/fuels/tests/scripts.rs
  packages/fuels/tests/scripts/basic_script/src/main.sw
  packages/fuels/tests/scripts/script_configurables/src/main.sw
  packages/fuels/tests/scripts/script_require/src/main.sw
  packages/fuels/tests/types/contracts/generics/src/main.sw
  packages/fuels/tests/types/contracts/results/src/main.sw
  packages/fuels/tests/types/contracts/tuples/src/main.sw
  packages/fuels/tests/types/contracts/vector_output/src/main.sw
  packages/fuels/tests/types/scripts/options_results/src/main.sw
  packages/fuels/tests/types/scripts/script_tuples/src/main.sw
  packages/fuels/tests/types_scripts.rs
Labels: bug, tech-debt

#1136 bug: unused generic type parameters
  docs/src/types/custom_types.md
  examples/types/src/lib.rs
  packages/fuels-code-gen/Cargo.toml
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/contract.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/function_generator.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/predicate.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/script.rs
  packages/fuels-code-gen/src/program_bindings/custom_types.rs
  packages/fuels-code-gen/src/program_bindings/custom_types/enums.rs
  packages/fuels-code-gen/src/program_bindings/custom_types/structs.rs
  packages/fuels-code-gen/src/program_bindings/custom_types/utils.rs
  packages/fuels-code-gen/src/program_bindings/resolved_type.rs
  packages/fuels-code-gen/src/program_bindings/utils.rs
  packages/fuels-core/src/codec/abi_decoder.rs
  packages/fuels-core/src/types/param_types.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-macros/src/derive/parameterize.rs
  packages/fuels-macros/src/derive/tokenizable.rs
  packages/fuels-macros/src/derive/utils.rs
  packages/fuels-macros/src/lib.rs
  packages/fuels-macros/src/parse_utils.rs
  packages/fuels/Cargo.toml
  packages/fuels/tests/types/contracts/generics/src/main.sw
  packages/fuels/tests/types_contracts.rs
  scripts/versions-replacer/src/main.rs
Labels: bug, abigen

#1161 feat: securely zero out `SecretKey`s from memory
  Cargo.toml
  packages/fuels-accounts/Cargo.toml
  packages/fuels-accounts/src/wallet.rs
  packages/fuels-core/Cargo.toml
  packages/fuels-core/src/types/transaction_builders.rs
Labels: tech-debt, package:core

#1159 feat: return `str` from contracts
  packages/fuels-core/src/codec/abi_decoder/bounded_decoder.rs
  packages/fuels-core/src/codec/abi_encoder.rs
  packages/fuels-core/src/types/param_types.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels/Forc.toml
  packages/fuels/tests/types/contracts/heap_type_in_enums/src/main.sw
  packages/fuels/tests/types/contracts/string_slice/Forc.toml
  packages/fuels/tests/types/contracts/string_slice/src/main.sw
  packages/fuels/tests/types_contracts.rs
Labels: tech-debt

#1164 fix: broken docs links
  README.md
  docs/src/abigen/the-json-abi-file.md
  docs/src/deploying/index.md
  docs/src/getting-started.md
Labels: bug, documentation

#1067 feat!: make functions return Result and implement Node Killer
  docs/src/connecting/short-lived.md
  examples/contracts/src/lib.rs
  examples/cookbook/src/lib.rs
  examples/predicates/src/lib.rs
  examples/providers/src/lib.rs
  examples/rust_bindings/src/lib.rs
  examples/wallets/src/lib.rs
  packages/fuels-accounts/Cargo.toml
  packages/fuels-accounts/src/provider.rs
  packages/fuels-accounts/src/wallet.rs
  packages/fuels-macros/src/setup_program_test/code_gen.rs
  packages/fuels-test-helpers/Cargo.toml
  packages/fuels-test-helpers/src/accounts.rs
  packages/fuels-test-helpers/src/fuel_bin_service.rs
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/node.rs
  packages/fuels-test-helpers/src/node_types.rs
  packages/fuels-test-helpers/src/service.rs
  packages/fuels-test-helpers/src/utils.rs
  packages/fuels/Cargo.toml
  packages/fuels/src/lib.rs
  packages/fuels/tests/bindings.rs
  packages/fuels/tests/configurables.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/from_token.rs
  packages/fuels/tests/logs.rs
  packages/fuels/tests/predicates.rs
  packages/fuels/tests/providers.rs
  packages/fuels/tests/scripts.rs
  packages/fuels/tests/storage.rs
  packages/fuels/tests/types_contracts.rs
  packages/fuels/tests/types_predicates.rs
  packages/fuels/tests/types_scripts.rs
  packages/fuels/tests/wallets.rs
Labels: breaking, dev-experience

#1166 feat: log/error on mismatch of client version and supported version
  Cargo.toml
  packages/fuels-accounts/Cargo.toml
  packages/fuels-accounts/src/lib.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-accounts/src/supported_versions.rs
Labels: enhancement, dev-experience

#1130 fix: ABI decoder crashing on certain inputs
  packages/fuels-core/src/codec/abi_decoder.rs
  packages/fuels-core/src/codec/abi_decoder/bounded_decoder.rs
  packages/fuels-core/src/codec/abi_encoder.rs
  packages/fuels-core/src/types/enum_variants.rs
  packages/fuels-core/src/types/param_types.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-programs/src/receipt_parser.rs
Labels: package:core, audit-report

#1169 feat: use `String` directly in `assert_eq`
  packages/fuels/tests/types/contracts/std_lib_string/src/main.sw
  packages/fuels/tests/types/predicates/predicate_std_lib_string/src/main.sw
  packages/fuels/tests/types/scripts/script_std_lib_string/src/main.sw
Labels: testing

#1156 fix: predicate witness data access
  packages/fuels-accounts/src/accounts_utils.rs
  packages/fuels-accounts/src/predicate.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-accounts/src/wallet.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-core/src/types/wrappers/transaction.rs
  packages/fuels/Forc.toml
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/predicates.rs
  packages/fuels/tests/predicates/predicate_witnesses/Forc.toml
  packages/fuels/tests/predicates/predicate_witnesses/src/main.sw
Labels: bug

#1173 fix: encode contract arguments with `gas_forwarded`
  packages/fuels-programs/src/call_utils.rs
  packages/fuels/tests/contracts.rs
Labels: bug

#1175 Revert "fix(ci): ignore testnet_hello_world test"
  packages/fuels/tests/providers.rs
Labels: tech-debt

#1176 Move health check after error collection
  packages/fuels-test-helpers/src/fuel_bin_service.rs
Labels: bug
