Repository FuelLabs/fuels-rs, pull requests merged in 2023-07, with the labels that each got.

#1026 docs: show README.md for fuels on crates.io
  Cargo.toml
  packages/fuels/Cargo.toml
Labels: documentation

#1014 feat: add `U256` support
  packages/fuels-code-gen/src/program_bindings/utils.rs
  packages/fuels-core/Cargo.toml
  packages/fuels-core/src/codec/abi_decoder.rs
  packages/fuels-core/src/codec/abi_encoder.rs
  packages/fuels-core/src/codec/function_selector.rs
  packages/fuels-core/src/types.rs
  packages/fuels-core/src/types/core.rs
  packages/fuels-core/src/types/core/identity.rs
  packages/fuels-core/src/types/core/u256.rs
  packages/fuels-core/src/types/param_types.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels/Forc.toml
  packages/fuels/tests/types/contracts/u256/Forc.toml
  packages/fuels/tests/types/contracts/u256/src/main.sw
  packages/fuels/tests/types/predicates/predicate_u256/Forc.toml
  packages/fuels/tests/types/predicates/predicate_u256/src/main.sw
  packages/fuels/tests/types/scripts/script_u256/Forc.toml
  packages/fuels/tests/types/scripts/script_u256/src/main.sw
  packages/fuels/tests/types_contracts.rs
  packages/fuels/tests/types_predicates.rs
  packages/fuels/tests/types_scripts.rs
Labels: enhancement

#1030 bug: reexport fuel_tx::Output
  packages/fuels-core/src/types/wrappers.rs
  packages/fuels/tests/imports.rs
Labels: bug

#1038 fix: export `TxPointer`, `UtxoId` and `Nonce`
  packages/fuels-core/src/types.rs
Labels: bug

#1036 feat: add `LogDecoder` getter for script instances
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/contract.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/script.rs
Labels: enhancement, abigen

#1037 feat: improve transaction builder error
  packages/fuels-core/src/types/errors.rs
  packages/fuels-core/src/types/transaction_builders.rs
Labels: enhancement

#1051 chore: remove pr automation
  .github/workflows/pull-requests.yml
Labels: bug

#1032 chore: use `fuel-asm` instead of `fuel-vm`
  packages/fuels-programs/Cargo.toml
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-test-helpers/Cargo.toml
  packages/fuels-test-helpers/src/node.rs
Labels: tech-debt

#1044 feat!: add support for string slices
  packages/fuels-code-gen/src/program_bindings/resolved_type.rs
  packages/fuels-core/src/codec/abi_decoder.rs
  packages/fuels-core/src/codec/abi_encoder.rs
  packages/fuels-core/src/codec/function_selector.rs
  packages/fuels-core/src/traits/parameterize.rs
  packages/fuels-core/src/traits/tokenizable.rs
  packages/fuels-core/src/types.rs
  packages/fuels-core/src/types/core/sized_ascii_string.rs
  packages/fuels-core/src/types/param_types.rs
  packages/fuels-programs/src/contract.rs
Labels: enhancement, breaking

#1056 docs: fix broken links
  README.md
  docs/src/abigen/the-json-abi-file.md
  docs/src/deploying/index.md
  docs/src/getting-started.md
Labels: bug, documentation

#1027 refactor(fuels): add test for more types in scripts
  packages/fuels/Forc.toml
  packages/fuels/tests/scripts.rs
  packages/fuels/tests/scripts/script_array/Forc.toml
  packages/fuels/tests/scripts/script_array/src/main.sw
  packages/fuels/tests/scripts/script_b256/Forc.toml
  packages/fuels/tests/scripts/script_b256/src/main.sw
  packages/fuels/tests/scripts/script_enum/Forc.toml
  packages/fuels/tests/scripts/script_enum/src/main.sw
  packages/fuels/tests/scripts/script_struct/Forc.toml
  packages/fuels/tests/scripts/script_struct/src/main.sw
Labels: tech-debt, testing

#1061 feat: macro recompile trigger
  examples/cookbook/src/lib.rs
  packages/fuels-accounts/src/lib.rs
  packages/fuels-code-gen/src/program_bindings/abigen.rs
  packages/fuels-code-gen/src/program_bindings/abigen/abigen_target.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/contract.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/function_generator.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/predicate.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/script.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/utils.rs
  packages/fuels-code-gen/src/program_bindings/abigen/configurables.rs
  packages/fuels-code-gen/src/program_bindings/abigen/logs.rs
  packages/fuels-code-gen/src/program_bindings/custom_types.rs
  packages/fuels-code-gen/src/program_bindings/custom_types/enums.rs
  packages/fuels-code-gen/src/program_bindings/custom_types/structs.rs
  packages/fuels-code-gen/src/program_bindings/custom_types/utils.rs
  packages/fuels-code-gen/src/program_bindings/utils.rs
  packages/fuels-code-gen/src/utils/source.rs
  packages/fuels-core/src/types.rs
  packages/fuels-core/src/types/wrappers/block.rs
  packages/fuels-core/src/types/wrappers/chain_info.rs
  packages/fuels-core/src/types/wrappers/message_proof.rs
  packages/fuels-core/src/types/wrappers/transaction_response.rs
  packages/fuels-macros/src/derive/utils.rs
  packages/fuels-test-helpers/src/node.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/providers.rs
  packages/fuels/tests/wallets.rs
Labels: bug
