Repository FuelLabs/fuels-rs, pull requests merged in 2023-08, with the labels that each got.

#1072 docs: fix `low_level_call` anchor
  docs/src/calling-contracts/low-level-calls.md
  packages/fuels/tests/contracts/contract_test/src/main.sw
Labels: documentation

#1070 feat: improve missing log decoder error
  packages/fuels-programs/src/logs.rs
  packages/fuels/tests/logs.rs
Labels: enhancement

#1057 feat(fuels-core): add CoinType::owner()
  packages/fuels-core/src/types/wrappers/coin_type.rs
Labels: enhancement

#1042 feat!: add `String` support
  .github/workflows/ci.yml
  examples/contracts/src/lib.rs
  packages/fuels-code-gen/src/program_bindings/resolved_type.rs
  packages/fuels-code-gen/src/program_bindings/utils.rs
  packages/fuels-core/src/codec/abi_decoder.rs
  packages/fuels-core/src/codec/abi_encoder.rs
  packages/fuels-core/src/codec/function_selector.rs
  packages/fuels-core/src/traits/parameterize.rs
  packages/fuels-core/src/traits/tokenizable.rs
  packages/fuels-core/src/types.rs
  packages/fuels-core/src/types/param_types.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels/Forc.toml
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/types/contracts/std_lib_string/Forc.toml
  packages/fuels/tests/types/contracts/std_lib_string/src/main.sw
  packages/fuels/tests/types/predicates/predicate_std_lib_string/Forc.toml
  packages/fuels/tests/types/predicates/predicate_std_lib_string/src/main.sw
  packages/fuels/tests/types/scripts/script_std_lib_string/Forc.toml
  packages/fuels/tests/types/scripts/script_std_lib_string/src/main.sw
  packages/fuels/tests/types_contracts.rs
  packages/fuels/tests/types_predicates.rs
  packages/fuels/tests/types_scripts.rs
Labels: enhancement

#1068 ci: add docs workflow
  .github/workflows/docs.yml
  .markdownlint.yaml
  .markdownlintignore
  docs/src/SUMMARY.md
  docs/src/abigen/index.md
  docs/src/abigen/the-abigen-macro.md
  docs/src/abigen/the-json-abi-file.md
  docs/src/accounts.md
  docs/src/calling-contracts/cost-estimation.md
  docs/src/calling-contracts/low-level-calls.md
  docs/src/calling-contracts/tx-dependency-estimation.md
  docs/src/calling-contracts/variable-outputs.md
  docs/src/cli/fuels-abi-cli.md
  docs/src/connecting/external-node.md
  docs/src/connecting/rocksdb.md
  docs/src/connecting/short-lived.md
  docs/src/contributing/tests-structure.md
  docs/src/cookbook/index.md
  docs/src/debugging/function-selector.md
  docs/src/debugging/index.md
  docs/src/deploying/configurable-constants.md
  docs/src/deploying/index.md
  docs/src/deploying/the-fuelvm-binary-file.md
  docs/src/getting-started.md
  docs/src/index.md
  docs/src/predicates/index.md
  docs/src/predicates/send-spend-predicate.md
  docs/src/running-scripts.md
  docs/src/testing/basics.md
  docs/src/testing/index.md
  docs/src/testing/the-setup-program-test-macro.md
  docs/src/types/bech32.md
  docs/src/types/vectors.md
  scripts/check-docs/tests/test_data/test_include_data.md
Labels: documentation, ci

#1074 feat: make message input w data persist when covering fees
  packages/fuels-accounts/src/accounts_utils.rs
  packages/fuels-accounts/src/predicate.rs
  packages/fuels-core/src/types/wrappers/input.rs
  packages/fuels/tests/predicates.rs
Labels: bug

#1077 chore: impl Ser + Deser + Hash for SizedAsciiString
  packages/fuels-core/src/types/core/sized_ascii_string.rs
Labels: enhancement

#1079 fix: string slice token conversion
  packages/fuels-core/src/traits/tokenizable.rs
Labels: bug, package:core

#1080 chore: `impl AsRef<[u8]> for SizedAsciiString`
  packages/fuels-core/src/types/core/sized_ascii_string.rs
Labels: enhancement

#1076 feat: add `build_tx` to `ScriptCallHandler`
  packages/fuels-programs/src/script_calls.rs
Labels: enhancement

#1075 chore: make get_contract_balances return AssetId and add provider.chain_id()
  examples/wallets/src/lib.rs
  packages/fuels-accounts/src/predicate.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/contract.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/predicates.rs
Labels: enhancement

#1084 chore: bump rust and deps versions
  .github/workflows/ci.yml
  Cargo.toml
Labels: tech-debt

#1073 separate send_transaction and get_receipts
  examples/cookbook/src/lib.rs
  packages/fuels-accounts/src/lib.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-programs/Cargo.toml
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/script_calls.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/scripts.rs
Labels: enhancement

#1095 chore: check doc links for private items in CI
  .github/workflows/ci.yml
  packages/fuels-code-gen/src/program_bindings/abigen.rs
Labels: tech-debt

#1096 style!: rename 'set_' to 'with_'
  docs/src/calling-contracts/other-contracts.md
  docs/src/calling-contracts/tx-dependency-estimation.md
  docs/src/deploying/configurable-constants.md
  docs/src/predicates/index.md
  docs/src/running-scripts.md
  examples/contracts/src/lib.rs
  examples/cookbook/src/lib.rs
  packages/fuels-accounts/src/lib.rs
  packages/fuels-accounts/src/predicate.rs
  packages/fuels-accounts/src/wallet.rs
  packages/fuels-code-gen/src/program_bindings/abigen/configurables.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-core/src/types/wrappers/transaction.rs
  packages/fuels-macros/src/setup_program_test/code_gen.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/logs.rs
  packages/fuels-programs/src/script_calls.rs
  packages/fuels/tests/configurables.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/logs.rs
  packages/fuels/tests/predicates.rs
  packages/fuels/tests/providers.rs
  packages/fuels/tests/scripts.rs
  packages/fuels/tests/storage.rs
Labels: enhancement

#1069 feat!: resolve witness indexes automatically
  docs/src/wallets/signing.md
  examples/cookbook/src/lib.rs
  packages/fuels-accounts/src/lib.rs
  packages/fuels-accounts/src/predicate.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-accounts/src/wallet.rs
  packages/fuels-core/Cargo.toml
  packages/fuels-core/src/types.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-core/src/types/wrappers/input.rs
  packages/fuels-core/src/types/wrappers/transaction.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/script_calls.rs
  packages/fuels-test-helpers/src/node.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/predicates.rs
  packages/fuels/tests/scripts.rs
  packages/fuels/tests/wallets.rs
Labels: enhancement

#1100 fix: validate multi-calls wrt to heap types
  docs/src/calling-contracts/multicalls.md
  packages/fuels-programs/src/contract.rs
  packages/fuels/tests/contracts.rs
Labels: bug

#1111 chore: replace deprecated `chrono` functions
  Cargo.toml
  packages/fuels-core/Cargo.toml
  packages/fuels-core/src/types/wrappers/block.rs
  packages/fuels-core/src/types/wrappers/transaction_response.rs
  packages/fuels/tests/providers.rs
Labels: bug

#1115 fix: pull max gas from provider
  packages/fuels-accounts/src/lib.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-core/src/utils/constants.rs
Labels: bug

#1112 feat: return result from `call_data!`
  docs/src/calling-contracts/low-level-calls.md
  examples/contracts/src/lib.rs
  examples/debugging/src/lib.rs
  packages/fuels-core/src/codec/function_selector.rs
  packages/fuels/tests/contracts.rs
Labels: tech-debt

#1119 feat: update tests to beta-4
  examples/providers/src/lib.rs
  packages/fuels/tests/providers.rs
Labels: documentation, testing
