Repository FuelLabs/fuels-rs, pull requests merged in 2023-09, with the labels that each got.

#1120 feat!: autoload storage slots
  docs/src/SUMMARY.md
  docs/src/deploying/storage-slots.md
  examples/contracts/src/lib.rs
  examples/cookbook/src/lib.rs
  packages/fuels-code-gen/src/program_bindings/abigen.rs
  packages/fuels-core/src/types/bech32.rs
  packages/fuels-core/src/types/core/sized_ascii_string.rs
  packages/fuels-core/src/types/param_types.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-macros/src/setup_program_test/code_gen.rs
  packages/fuels-programs/Cargo.toml
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/storage.rs
Labels: bug, enhancement

#1103 docs: add CONTRIBUTING.md
  docs/src/SUMMARY.md
  docs/src/contributing/CONTRIBUTING.md
  docs/src/contributing/contributing.md
Labels: documentation

#1122 feat: use `REG_CGAS` as default forwarded gas
  examples/contracts/src/lib.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/providers.rs
Labels: tech-debt

#1124 fix!: predicate cost estimation
  packages/fuels-accounts/src/accounts_utils.rs
  packages/fuels-accounts/src/predicate.rs
  packages/fuels-accounts/src/wallet.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels/tests/predicates.rs
  packages/fuels/tests/providers.rs
Labels: bug

#1035 feat: add retry mechanism
  Cargo.toml
  docs/src/SUMMARY.md
  docs/src/calling-contracts/index.md
  docs/src/calling-contracts/multicalls.md
  docs/src/connecting/retrying.md
  docs/src/running-scripts.md
  examples/contracts/src/lib.rs
  examples/cookbook/src/lib.rs
  examples/predicates/src/lib.rs
  examples/providers/src/lib.rs
  examples/wallets/src/lib.rs
  packages/fuels-accounts/src/lib.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-accounts/src/provider/retry_util.rs
  packages/fuels-accounts/src/provider/retryable_client.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/contract.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/script.rs
  packages/fuels-code-gen/src/program_bindings/abigen/logs.rs
  packages/fuels-core/Cargo.toml
  packages/fuels-core/src/codec.rs
  packages/fuels-core/src/codec/logs.rs
  packages/fuels-core/src/types.rs
  packages/fuels-core/src/types/tx_status.rs
  packages/fuels-programs/Cargo.toml
  packages/fuels-programs/src/call_response.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/lib.rs
  packages/fuels-programs/src/script_calls.rs
  packages/fuels-programs/src/submit_response.rs
  packages/fuels-test-helpers/src/accounts.rs
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/node.rs
  packages/fuels/Cargo.toml
  packages/fuels/src/lib.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/predicates.rs
  packages/fuels/tests/providers.rs
  packages/fuels/tests/scripts.rs
  packages/fuels/tests/types_predicates.rs
  packages/fuels/tests/wallets.rs
Labels: enhancement, breaking

#1140 chore(deps): remove unused deps, add corresponding CI check
  .github/workflows/ci.yml
  packages/fuels-accounts/Cargo.toml
  packages/fuels-code-gen/Cargo.toml
  packages/fuels-core/Cargo.toml
  packages/fuels-macros/Cargo.toml
  packages/fuels-programs/Cargo.toml
  packages/fuels-test-helpers/Cargo.toml
Labels: tech-debt, P: low

#1143 fix(ci): ignore testnet_hello_world test
  packages/fuels/tests/providers.rs
Labels: bug, ci

#1121 feat: pull tx param defaults from network
  docs/src/calling-contracts/tx-params.md
  docs/src/connecting/external-node.md
  examples/cookbook/src/lib.rs
  packages/fuels-accounts/src/lib.rs
  packages/fuels-accounts/src/predicate.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-accounts/src/wallet.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-core/src/types/wrappers/block.rs
  packages/fuels-core/src/types/wrappers/chain_info.rs
  packages/fuels-core/src/types/wrappers/node_info.rs
  packages/fuels-core/src/types/wrappers/transaction.rs
  packages/fuels-core/src/utils/constants.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/script_calls.rs
  packages/fuels/tests/predicates.rs
  packages/fuels/tests/providers.rs
  packages/fuels/tests/wallets.rs
Labels: enhancement

#1146 docs: use correct method names
  docs/src/running-scripts.md
Labels: documentation
