Repository FuelLabs/fuels-rs, pull requests merged in 2023-12, with the labels that each got.

#1225 chore: use `forc 0.48`
  .github/workflows/ci.yml
  examples/contracts/src/lib.rs
  packages/fuels/Forc.toml
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/providers.rs
Labels: ci

#1234 refactor: use receipts from `TransactionStatus`
  packages/fuels-accounts/Cargo.toml
  packages/fuels-accounts/src/provider.rs
  packages/fuels-accounts/src/provider/retryable_client.rs
  packages/fuels-core/src/types/tx_status.rs
Labels: tech-debt

#1183 chore: add test for compute_calls_instructions_len
  packages/fuels-programs/src/call_utils.rs
Labels: testing, package:contracts
