Repository FuelLabs/fuels-rs, pull requests merged in 2023-03, with the labels that each got.

#859 Resolve cyclic deps
  .github/workflows/ci.yml
  packages/fuels-core/Cargo.toml
  packages/fuels-core/src/abi_decoder.rs
  packages/fuels-core/src/abi_encoder.rs
  packages/fuels-core/src/function_selector.rs
  packages/fuels-core/src/utils.rs
  packages/fuels-signers/Cargo.toml
  packages/fuels-signers/src/lib.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/Cargo.toml
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-types/src/param_types.rs
  packages/fuels/tests/wallets.rs
Labels: tech-debt, testing

#876 fix minor typo
  docs/src/calling-contracts/cost-estimation.md
Labels: documentation, P: low

#860 refactor: contract deployment configuration
  docs/src/abigen/the-abigen-macro.md
  docs/src/calling-contracts/tx-params.md
  docs/src/contracts/configurable-constants.md
  docs/src/getting-started/contracts.md
  examples/contracts/src/lib.rs
  examples/cookbook/src/lib.rs
  examples/wallets/src/lib.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/predicate.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/script.rs
  packages/fuels-macros/src/setup_contract_test/code_gen.rs
  packages/fuels-programs/Cargo.toml
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/lib.rs
  packages/fuels-programs/src/script_calls.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-types/src/constants.rs
  packages/fuels-types/src/lib.rs
  packages/fuels-types/src/parameters.rs
  packages/fuels-types/src/transaction.rs
  packages/fuels/src/lib.rs
  packages/fuels/tests/configurables.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/logs.rs
  packages/fuels/tests/providers.rs
  packages/fuels/tests/scripts.rs
  packages/fuels/tests/storage.rs
  packages/fuels/tests/types.rs
  packages/fuels/tests/wallets.rs
Labels: breaking

#872 feat: type path support (`forc` flag `--json-abi-with-callpaths`)
  .github/workflows/ci.yml
  docs/src/abigen/the-abigen-macro.md
  examples/rust_bindings/Cargo.toml
  examples/rust_bindings/src/rust_bindings_formatted.rs
  packages/fuels-code-gen/src/program_bindings/abi_types.rs
  packages/fuels-code-gen/src/program_bindings/abigen.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/contract.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/function_generator.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/predicate.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/script.rs
  packages/fuels-code-gen/src/program_bindings/abigen/configurables.rs
  packages/fuels-code-gen/src/program_bindings/abigen/logs.rs
  packages/fuels-code-gen/src/program_bindings/custom_types.rs
  packages/fuels-code-gen/src/program_bindings/custom_types/enums.rs
  packages/fuels-code-gen/src/program_bindings/custom_types/structs.rs
  packages/fuels-code-gen/src/program_bindings/custom_types/utils.rs
  packages/fuels-code-gen/src/program_bindings/generated_code.rs
  packages/fuels-code-gen/src/program_bindings/resolved_type.rs
  packages/fuels-code-gen/src/program_bindings/utils.rs
  packages/fuels-code-gen/src/utils/type_path.rs
  packages/fuels-core/src/abi_decoder.rs
  packages/fuels-core/src/function_selector.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-signers/src/provider.rs
  packages/fuels-signers/src/wallet.rs
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/node.rs
  packages/fuels-types/src/param_types.rs
  packages/fuels/Cargo.toml
  packages/fuels/Forc.toml
  packages/fuels/tests/bindings.rs
  packages/fuels/tests/bindings/type_paths/Forc.toml
  packages/fuels/tests/bindings/type_paths/src/another_lib.sw
  packages/fuels/tests/bindings/type_paths/src/contract_a_types.sw
  packages/fuels/tests/bindings/type_paths/src/main.sw
  packages/wasm-tests/src/lib.rs
Labels: bug, enhancement

#868 feat: support `Bytes` type return from contract
  packages/fuels-code-gen/src/program_bindings/custom_types.rs
  packages/fuels-code-gen/src/program_bindings/resolved_type.rs
  packages/fuels-code-gen/src/program_bindings/utils.rs
  packages/fuels-core/src/abi_decoder.rs
  packages/fuels-core/src/abi_encoder.rs
  packages/fuels-core/src/function_selector.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-types/src/core.rs
  packages/fuels-types/src/core/bytes.rs
  packages/fuels-types/src/param_types.rs
  packages/fuels-types/src/traits/parameterize.rs
  packages/fuels-types/src/traits/tokenizable.rs
  packages/fuels/Forc.toml
  packages/fuels/tests/types.rs
  packages/fuels/tests/types/bytes/Forc.toml
  packages/fuels/tests/types/bytes/src/main.sw
Labels: enhancement

#900 ci: add clippy check without all features
  .github/workflows/ci.yml
  packages/fuels-test-helpers/src/node.rs
Labels: ci

#885 refactor!: improve log decoding and simplify `ParamType`
  examples/rust_bindings/src/rust_bindings_formatted.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/contract.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/script.rs
  packages/fuels-code-gen/src/program_bindings/abigen/logs.rs
  packages/fuels-core/src/abi_decoder.rs
  packages/fuels-core/src/abi_encoder.rs
  packages/fuels-core/src/function_selector.rs
  packages/fuels-core/src/lib.rs
  packages/fuels-core/src/traits.rs
  packages/fuels-core/src/traits/decodable_log.rs
  packages/fuels-core/src/utils.rs
  packages/fuels-macros/src/derive/parameterize.rs
  packages/fuels-macros/src/parse_utils.rs
  packages/fuels-programs/src/call_response.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/logs.rs
  packages/fuels-types/src/core.rs
  packages/fuels-types/src/core/bits.rs
  packages/fuels-types/src/enum_variants.rs
  packages/fuels-types/src/param_types.rs
  packages/fuels-types/src/traits/parameterize.rs
  packages/fuels/tests/logs.rs
Labels: tech-debt, breaking

#906 Delete `provider` from with `with_account` function
  examples/rust_bindings/src/rust_bindings_formatted.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/contract.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/script.rs
Labels: enhancement

#913 refactor!: `fuels` wasm-offending packages/reexports hidden behind `std` flag
  packages/fuels-code-gen/src/program_bindings/abigen.rs
  packages/fuels-code-gen/src/program_bindings/custom_types.rs
  packages/fuels-code-gen/src/program_bindings/custom_types/enums.rs
  packages/fuels-code-gen/src/program_bindings/custom_types/structs.rs
  packages/fuels/Cargo.toml
  packages/fuels/src/lib.rs
  packages/wasm-tests/Cargo.toml
  packages/wasm-tests/src/lib.rs
Labels: enhancement, tech-debt, breaking

#911 bug: storage slots have to be sorted in a create tx
  packages/fuels-programs/src/contract.rs
  packages/fuels-types/src/transaction_builders.rs
Labels: bug
