Repository FuelLabs/fuels-rs, pull requests merged in 2024-05, with the labels that each got.

#1357 feat!: remove legacy decoding
  .github/workflows/ci.yml
  docs/src/debugging/function-selector.md
  docs/src/types/evm_address.md
  docs/src/types/string.md
  examples/contracts/Cargo.toml
  examples/contracts/src/lib.rs
  examples/debugging/Cargo.toml
  examples/debugging/src/lib.rs
  examples/rust_bindings/src/rust_bindings_formatted.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-accounts/src/provider/retryable_client.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/contract.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/function_generator.rs
  packages/fuels-code-gen/src/program_bindings/custom_types/utils.rs
  packages/fuels-code-gen/src/program_bindings/utils.rs
  packages/fuels-core/Cargo.toml
  packages/fuels-core/src/codec.rs
  packages/fuels-core/src/codec/abi_decoder.rs
  packages/fuels-core/src/codec/abi_decoder/decode_as_debug_str.rs
  packages/fuels-core/src/codec/abi_decoder/legacy_bounded_decoder.rs
  packages/fuels-core/src/codec/abi_encoder.rs
  packages/fuels-core/src/codec/abi_encoder/configurables_bounded_encoder.rs
  packages/fuels-core/src/codec/function_selector.rs
  packages/fuels-core/src/codec/logs.rs
  packages/fuels-core/src/types.rs
  packages/fuels-core/src/types/param_types.rs
  packages/fuels-core/src/types/param_types/debug_with_depth.rs
  packages/fuels-core/src/types/param_types/param_type.rs
  packages/fuels-programs/Cargo.toml
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/receipt_parser.rs
  packages/fuels-programs/src/script_calls.rs
  packages/fuels/Cargo.toml
  packages/fuels/Forc.toml
  packages/fuels/tests/bindings.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/contracts/liquidity_pool/src/main.sw
  packages/fuels/tests/contracts/low_level_caller/src/main.sw
  packages/fuels/tests/from_token.rs
  packages/fuels/tests/logs.rs
  packages/fuels/tests/predicates.rs
  packages/fuels/tests/providers.rs
  packages/fuels/tests/types_contracts.rs
  packages/fuels/tests/types_scripts.rs
  packages/wasm-tests/Cargo.toml
  packages/wasm-tests/src/lib.rs
Labels: big, breaking

#1358 chore: adapt to forc `0.56.0` again (CI got stuck)
  .github/workflows/ci.yml
  examples/contracts/src/lib.rs
  examples/cookbook/src/lib.rs
  packages/fuels-core/src/types/core/identity.rs
  packages/fuels/Forc.toml
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/contracts/lib_contract_caller/src/main.sw
  packages/fuels/tests/contracts/liquidity_pool/src/main.sw
  packages/fuels/tests/contracts/token_ops/src/main.sw
  packages/fuels/tests/logs.rs
  packages/fuels/tests/providers.rs
  packages/fuels/tests/scripts.rs
  packages/fuels/tests/scripts/transfer_script/src/main.sw
Labels: enhancement, tech-debt

#1336 feat: upgrade fuel-core to 0.26.0
  .github/workflows/ci.yml
  Cargo.toml
  packages/fuels-accounts/src/provider.rs
  packages/fuels-accounts/src/provider/supported_versions.rs
  packages/fuels-core/src/codec/abi_encoder/configurables_bounded_encoder.rs
  packages/fuels-core/src/types.rs
  packages/fuels-core/src/types/core/raw_slice.rs
  packages/fuels-core/src/types/core/u256.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-core/src/types/wrappers/block.rs
  packages/fuels-core/src/types/wrappers/message.rs
  packages/fuels-core/src/types/wrappers/transaction.rs
  packages/fuels-core/src/types/wrappers/transaction_response.rs
  packages/fuels-core/src/utils/offsets.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-programs/src/script_calls.rs
  packages/fuels-test-helpers/src/fuel_bin_service.rs
  packages/fuels/tests/providers.rs
Labels: enhancement

#1347 feat!: improve error on malformed `abi`
  packages/fuels-code-gen/src/program_bindings.rs
  packages/fuels-code-gen/src/program_bindings/abigen.rs
  packages/fuels-code-gen/src/program_bindings/abigen/abigen_target.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/utils.rs
  packages/fuels-code-gen/src/utils.rs
  packages/fuels-code-gen/src/utils/source.rs
  packages/fuels-macros/src/abigen/parsing.rs
  packages/fuels-macros/src/lib.rs
  packages/fuels-macros/src/setup_program_test/code_gen.rs
  packages/fuels-macros/tests/ui/abigen/invalid_abi_path.rs
  packages/fuels-macros/tests/ui/abigen/invalid_abi_path.stderr
  packages/fuels-macros/tests/ui/abigen/malformed_abi.rs
  packages/fuels-macros/tests/ui/abigen/malformed_abi.stderr
  packages/fuels-macros/tests/ui/setup_program_test/duplicate_wallet_command.rs
  packages/fuels-macros/tests/ui/setup_program_test/duplicate_wallet_names.rs
  packages/fuels-macros/tests/ui/setup_program_test/invalid_path.rs
  packages/fuels-macros/tests/ui/setup_program_test/invalid_path.stderr
  packages/fuels-macros/tests/ui/setup_program_test/invalid_project_path.rs
  packages/fuels-macros/tests/ui/setup_program_test/invalid_project_path.stderr
Labels: abigen

#1341 chore: add echo string test
  packages/fuels/tests/types/contracts/std_lib_string/src/main.sw
  packages/fuels/tests/types_contracts.rs
Labels: enhancement

#1338 feat!: remove legacy encoding
  .github/workflows/ci.yml
  docs/src/calling-contracts/low-level-calls.md
  docs/src/codec/encoding.md
  examples/codec/src/lib.rs
  examples/contracts/src/lib.rs
  packages/fuels-accounts/src/predicate.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/predicate.rs
  packages/fuels-code-gen/src/program_bindings/abigen/configurables.rs
  packages/fuels-core/Cargo.toml
  packages/fuels-core/src/codec.rs
  packages/fuels-core/src/codec/abi_decoder.rs
  packages/fuels-core/src/codec/abi_encoder.rs
  packages/fuels-core/src/codec/abi_encoder/bounded_encoder.rs
  packages/fuels-core/src/codec/abi_encoder/configurables_bounded_encoder.rs
  packages/fuels-core/src/codec/function_selector.rs
  packages/fuels-core/src/types.rs
  packages/fuels-core/src/types/param_types.rs
  packages/fuels-core/src/types/param_types/enum_variants.rs
  packages/fuels-core/src/types/param_types/param_type.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-core/src/types/unresolved_bytes.rs
  packages/fuels-core/src/types/wrappers/input.rs
  packages/fuels-core/src/utils/offsets.rs
  packages/fuels-programs/Cargo.toml
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/script_calls.rs
  packages/fuels/Forc.toml
  packages/fuels/tests/bindings.rs
  packages/fuels/tests/configurables.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/contracts/configurables/src/main.sw
  packages/fuels/tests/contracts/needs_custom_decoder/src/main.sw
  packages/fuels/tests/logs.rs
  packages/fuels/tests/logs/script_heap_logs/Forc.toml
  packages/fuels/tests/logs/script_heap_logs/src/main.sw
  packages/fuels/tests/logs/script_needs_custom_decoder_logging/src/main.sw
  packages/fuels/tests/predicates.rs
  packages/fuels/tests/predicates/predicate_configurables/src/main.sw
  packages/fuels/tests/providers.rs
  packages/fuels/tests/scripts.rs
  packages/fuels/tests/scripts/script_configurables/src/main.sw
  packages/fuels/tests/scripts/script_needs_custom_decoder/src/main.sw
  packages/fuels/tests/types_predicates.rs
  packages/fuels/tests/types_scripts.rs
  packages/wasm-tests/src/lib.rs
Labels: big, breaking, blocked

#1366 bug: fix estimation issue
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels/Forc.toml
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/contracts/msg_amount/src/main.sw
  packages/fuels/tests/contracts/msg_methods/Forc.toml
  packages/fuels/tests/contracts/msg_methods/src/main.sw
Labels: bug

#1368 bug: fix revert id
  packages/fuels-accounts/Cargo.toml
  packages/fuels-accounts/src/provider.rs
  packages/fuels-core/Cargo.toml
  packages/fuels-core/src/types/tx_status.rs
  packages/fuels/tests/logs.rs
Labels: bug

#1370 chore: update `wallet.rs` in-line BIP doc
  packages/fuels-accounts/src/wallet.rs
Labels: documentation

#1379 chore: bump `forc` to `0.58.0`
  .github/workflows/ci.yml
  e2e/Forc.toml
Labels: dev-experience

#1377 chore: export `Hasher` through `fuels::crypto`
  packages/fuels/src/lib.rs
Labels: dev-experience

#1386 chore: update forc to 0.59.0
  .github/workflows/ci.yml
  e2e/Forc.toml
Labels: tech-debt

#1388 chore: bump `forc` to `0.60.0`
  .github/workflows/ci.yml
  e2e/tests/providers.rs
  e2e/tests/types_contracts.rs
  examples/contracts/src/lib.rs
Labels: tech-debt

#1390 feat: use doc strings from the `abi` in `abigen`
  Cargo.toml
  e2e/sway/contracts/contract_test/src/main.sw
  e2e/sway/scripts/basic_script/src/main.sw
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/contract.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/function_generator.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/predicate.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/script.rs
Labels: tech-debt

#1391 refactor: remove `provider` from `ScriptCallHandler`
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/script.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/script_calls.rs
  packages/fuels-programs/src/submit_response.rs
Labels: tech-debt

#1398 bug: e2e build script
  Cargo.toml
  e2e/Cargo.toml
  e2e/build.rs
Labels: bug

#1400 bug: await tx committal
  e2e/tests/providers.rs
Labels: bug

#1403 bug: fix cargo publish
  e2e/Cargo.toml
  e2e/build.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-accounts/src/provider/supported_fuel_core_version.rs
  packages/fuels-accounts/src/provider/supported_versions.rs
  scripts/fuel-core-version/Cargo.toml
  scripts/fuel-core-version/src/main.rs
  scripts/fuel-core-version/version.rs
Labels: bug
