Repository FuelLabs/fuels-rs, pull requests merged in 2024-01, with the labels that each got.

#1241 refactor!: signing and the `Signer` trait
  docs/src/custom-transactions/transaction-builders.md
  docs/src/wallets/signing.md
  examples/contracts/src/lib.rs
  examples/cookbook/src/lib.rs
  examples/predicates/src/lib.rs
  examples/providers/src/lib.rs
  examples/wallets/src/lib.rs
  packages/fuels-accounts/src/account.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-accounts/src/wallet.rs
  packages/fuels-core/Cargo.toml
  packages/fuels-core/src/traits.rs
  packages/fuels-core/src/traits/signer.rs
  packages/fuels-core/src/types/errors.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-core/src/types/wrappers/transaction.rs
  packages/fuels-core/src/utils.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/script_calls.rs
  packages/fuels-test-helpers/Cargo.toml
  packages/fuels-test-helpers/src/accounts.rs
  packages/fuels/Cargo.toml
  packages/fuels/src/lib.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/predicates.rs
  packages/fuels/tests/providers.rs
  packages/fuels/tests/scripts.rs
  packages/fuels/tests/wallets.rs
Labels: enhancement

#1250 chore: remove hybrid trigger
  packages/fuels-test-helpers/src/fuel_bin_service.rs
  packages/fuels-test-helpers/src/node_types.rs
Labels: tech-debt

#1259 feat!: add support for experimental encoding in logs
  .github/workflows/ci.yml
  packages/fuels-core/src/codec/abi_decoder.rs
  packages/fuels-core/src/codec/abi_decoder/bounded_decoder.rs
  packages/fuels-core/src/codec/abi_decoder/experimental_bounded_decoder.rs
  packages/fuels-core/src/codec/abi_encoder.rs
  packages/fuels-core/src/codec/logs.rs
  packages/fuels-core/src/types.rs
  packages/fuels-core/src/types/core/raw_slice.rs
  packages/fuels-core/src/types/param_types.rs
  packages/fuels/Forc.toml
  packages/fuels/tests/contracts/needs_custom_decoder/src/main.sw
  packages/fuels/tests/logs.rs
  packages/fuels/tests/logs/contract_logs/src/main.sw
  packages/fuels/tests/logs/contract_logs_abi/src/main.sw
  packages/fuels/tests/logs/script_experimental_logs/Forc.toml
  packages/fuels/tests/logs/script_experimental_logs/src/main.sw
  packages/fuels/tests/logs/script_logs/src/main.sw
  packages/fuels/tests/scripts/script_needs_custom_decoder/src/main.sw
  packages/fuels/tests/types/contracts/raw_slice/src/main.sw
  packages/fuels/tests/types/predicates/predicate_raw_slice/src/main.sw
  packages/fuels/tests/types_contracts.rs
Labels: enhancement, big, dev-experience
