Repository FuelLabs/fuels-rs, pull requests merged in 2024-12, with the labels that each got.

#1549 feat: check if coin already in cache
  Cargo.toml
  e2e/tests/providers.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-accounts/src/provider/supported_fuel_core_version.rs
Labels: dev-experience

#1553 feat: `extract_contract_call_data` function pub modifier
  packages/fuels-programs/src/calls/receipt_parser.rs
Labels: dev-experience

#1554 `WalletUnlocked` function to expose `SecretKey` under `test-helpers` feature-flag
  packages/fuels-accounts/Cargo.toml
  packages/fuels-accounts/src/wallet.rs
Labels: testing, dev-experience

#1542 feat: script transaction human readable formatting
  Cargo.toml
  docs/src/SUMMARY.md
  docs/src/debugging/decoding-script-transactions.md
  e2e/sway/scripts/script_struct/src/main.sw
  e2e/sway/types/contracts/nested_structs/src/main.sw
  e2e/tests/debug_utils.rs
  examples/contracts/src/lib.rs
  packages/fuels-core/src/codec.rs
  packages/fuels-core/src/codec/abi_decoder.rs
  packages/fuels-core/src/codec/abi_formatter.rs
  packages/fuels-programs/Cargo.toml
  packages/fuels-programs/src/assembly.rs
  packages/fuels-programs/src/assembly/contract_call.rs
  packages/fuels-programs/src/assembly/cursor.rs
  packages/fuels-programs/src/assembly/script_and_predicate_loader.rs
  packages/fuels-programs/src/calls/call_handler.rs
  packages/fuels-programs/src/calls/contract_call.rs
  packages/fuels-programs/src/calls/utils.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/contract/loader.rs
  packages/fuels-programs/src/debug.rs
  packages/fuels-programs/src/executable.rs
  packages/fuels-programs/src/lib.rs
  packages/fuels-programs/src/utils.rs
  packages/fuels/Cargo.toml
  packages/fuels/src/lib.rs
  wasm-tests/Cargo.toml
  wasm-tests/src/lib.rs
Labels: enhancement
