Repository FuelLabs/fuels-rs, pull requests merged in 2024-07, with the labels that each got.

#1448 feat: finalize support for `raw_slice` and `string_slice`
  .github/workflows/ci.yml
  e2e/Forc.toml
  e2e/sway/types/contracts/string_slice/src/main.sw
  e2e/sway/types/predicates/predicate_string_slice/Forc.toml
  e2e/sway/types/predicates/predicate_string_slice/src/main.sw
  e2e/sway/types/scripts/script_raw_slice/src/main.sw
  e2e/sway/types/scripts/script_std_lib_string/src/main.sw
  e2e/sway/types/scripts/script_string_slice/Forc.toml
  e2e/sway/types/scripts/script_string_slice/src/main.sw
  e2e/tests/providers.rs
  e2e/tests/storage.rs
  e2e/tests/types_contracts.rs
  e2e/tests/types_predicates.rs
  e2e/tests/types_scripts.rs
  examples/contracts/src/lib.rs
Labels: tech-debt, blocked

#1453 chore: use `forc` `0.61.2`
  .github/workflows/ci.yml
  e2e/tests/providers.rs
  examples/contracts/src/lib.rs
Labels: tech-debt

#1458 feat: add max fee estimation tolerance
  e2e/tests/contracts.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-programs/src/calls/traits/transaction_tuner.rs
  packages/fuels-programs/src/calls/utils.rs
  packages/fuels-programs/src/contract.rs
Labels: enhancement

#1459 chore: update `forc build` path in docs
  README.md
  docs/src/getting-started.md
Labels: documentation

#1412 feat!: unfunded read only calls
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  docs/src/SUMMARY.md
  docs/src/calling-contracts/read-only.md
  docs/src/calling-contracts/simulation.md
  docs/src/custom-transactions/transaction-builders.md
  e2e/tests/contracts.rs
  e2e/tests/logs.rs
  e2e/tests/scripts.rs
  examples/codec/Cargo.toml
  examples/contracts/Cargo.toml
  examples/contracts/src/lib.rs
  examples/cookbook/Cargo.toml
  examples/debugging/Cargo.toml
  examples/macros/Cargo.toml
  examples/predicates/Cargo.toml
  examples/providers/Cargo.toml
  examples/rust_bindings/Cargo.toml
  examples/types/Cargo.toml
  examples/wallets/Cargo.toml
  packages/fuels-core/src/types/core/sized_ascii_string.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-core/src/types/transaction_builders/script_tx_estimator.rs
  packages/fuels-programs/src/calls.rs
  packages/fuels-programs/src/calls/call_handler.rs
  packages/fuels/src/lib.rs
Labels: enhancement

#1464 bug!: accounts now cover max fee increase due to tolerance
  e2e/tests/contracts.rs
  packages/fuels-accounts/src/accounts_utils.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-core/src/types/transaction_builders.rs
Labels: bug

#1466 chore: use `forc` `0.62.0`
  .github/workflows/ci.yml
  e2e/tests/providers.rs
  examples/contracts/src/lib.rs
Labels: tech-debt

#1467 chore: bump rust to 1.79.0
  .github/workflows/ci.yml
  Cargo.toml
Labels: tech-debt

#1468 ci: bump (and pin) rust-cache action to v2.7.3
  .github/workflows/ci.yml
Labels: bug, ci

#1473 feat!: account impersonation
  docs/src/accounts.md
  e2e/tests/providers.rs
  examples/contracts/src/lib.rs
  packages/fuels-accounts/src/impersonated_account.rs
  packages/fuels-accounts/src/lib.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels/src/lib.rs
Labels: enhancement

#1474 feat: remove legacy code for abi without callpaths
  .github/workflows/ci.yml
  ci_checks.sh
  docs/src/abigen/the-abigen-macro.md
  e2e/Cargo.toml
  e2e/tests/bindings.rs
  packages/fuels-code-gen/src/program_bindings/custom_types.rs
  packages/fuels-code-gen/src/program_bindings/resolved_type.rs
  packages/fuels-code-gen/src/program_bindings/utils.rs
  packages/fuels-core/src/types/param_types/from_type_application.rs
Labels: tech-debt
