Repository FuelLabs/fuels-rs, pull requests merged in 2024-04, with the labels that each got.

#1303 feat: experimental encoding for contracts, scripts and predicates
  .github/workflows/ci.yml
  docs/src/types/custom_types.md
  examples/contracts/Cargo.toml
  examples/contracts/src/lib.rs
  examples/debugging/Cargo.toml
  examples/debugging/src/lib.rs
  packages/fuels-core/Cargo.toml
  packages/fuels-core/src/codec.rs
  packages/fuels-core/src/codec/abi_decoder.rs
  packages/fuels-core/src/codec/abi_decoder/decode_as_debug_str.rs
  packages/fuels-core/src/codec/abi_decoder/experimental_bounded_decoder.rs
  packages/fuels-core/src/codec/abi_encoder.rs
  packages/fuels-core/src/codec/abi_encoder/bounded_encoder.rs
  packages/fuels-core/src/codec/abi_encoder/experimental_bounded_encoder.rs
  packages/fuels-core/src/codec/function_selector.rs
  packages/fuels-core/src/codec/logs.rs
  packages/fuels-core/src/types.rs
  packages/fuels-core/src/types/core/bytes.rs
  packages/fuels-core/src/types/param_types/param_type.rs
  packages/fuels-core/src/types/token.rs
  packages/fuels-programs/Cargo.toml
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/receipt_parser.rs
  packages/fuels/Cargo.toml
  packages/fuels/Forc.toml
  packages/fuels/tests/bindings.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/contracts/lib_contract/src/main.sw
  packages/fuels/tests/from_token.rs
  packages/fuels/tests/logs.rs
  packages/fuels/tests/predicates.rs
  packages/fuels/tests/predicates/signatures/src/main.sw
  packages/fuels/tests/providers.rs
  packages/fuels/tests/scripts.rs
  packages/fuels/tests/types/contracts/heap_types/Forc.toml
  packages/fuels/tests/types/contracts/heap_types/src/main.sw
  packages/fuels/tests/types/contracts/type_inside_enum/src/main.sw
  packages/fuels/tests/types/scripts/script_heap_types/Forc.toml
  packages/fuels/tests/types/scripts/script_heap_types/src/main.sw
  packages/fuels/tests/types_contracts.rs
  packages/fuels/tests/types_scripts.rs
  packages/wasm-tests/Cargo.toml
  packages/wasm-tests/src/lib.rs
Labels: big, dev-experience

#1322 chore: remove broken CI steps
  .github/workflows/opened-issues-triage.yml
  .github/workflows/releasy-dependency-commits.yml
  .github/workflows/releasy-self-commits.yml
Labels: ci

#1312 chore: bump `forc` to `0.52.1`
  .github/workflows/ci.yml
Labels: tech-debt

#1313 feat!: get base `AssetId` from provider
  examples/contracts/src/lib.rs
  examples/cookbook/src/lib.rs
  examples/predicates/src/lib.rs
  examples/providers/src/lib.rs
  examples/wallets/src/lib.rs
  packages/fuels-accounts/src/account.rs
  packages/fuels-accounts/src/accounts_utils.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-core/src/types/wrappers/coin_type.rs
  packages/fuels-core/src/types/wrappers/input.rs
  packages/fuels-core/src/types/wrappers/transaction.rs
  packages/fuels-core/src/utils/constants.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-test-helpers/src/accounts.rs
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/wallets_config.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/contracts/low_level_caller/src/main.sw
  packages/fuels/tests/predicates.rs
  packages/fuels/tests/predicates/swap/src/main.sw
  packages/fuels/tests/providers.rs
  packages/fuels/tests/scripts.rs
  packages/fuels/tests/types_predicates.rs
  packages/fuels/tests/wallets.rs
Labels: tech-debt, P: high, breaking

#1325 chore: remove deprecation error for `U256`
  packages/fuels-code-gen/src/program_bindings/resolved_type.rs
Labels: tech-debt

#1319 feat!: upgrade fuel-core to 24.2
  .github/workflows/ci.yml
  Cargo.toml
  examples/contracts/src/lib.rs
  examples/cookbook/src/lib.rs
  examples/types/src/lib.rs
  packages/fuels-accounts/src/account.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-accounts/src/provider/supported_versions.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-core/src/types/wrappers/block.rs
  packages/fuels-core/src/types/wrappers/coin.rs
  packages/fuels-core/src/types/wrappers/node_info.rs
  packages/fuels-core/src/types/wrappers/transaction.rs
  packages/fuels-core/src/utils/offsets.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-test-helpers/Cargo.toml
  packages/fuels-test-helpers/src/accounts.rs
  packages/fuels-test-helpers/src/fuel_bin_service.rs
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels-test-helpers/src/node_types.rs
  packages/fuels-test-helpers/src/service.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/providers.rs
  packages/fuels/tests/scripts.rs
Labels: enhancement

#1332 chore(ci): only show failed tests with `nextest`
  .github/workflows/ci.yml
Labels: ci

#1330 chore: bump `forc` to `0.54.0` and re-enable `generics` tests
  .github/workflows/ci.yml
  docs/src/types/custom_types.md
  examples/contracts/src/lib.rs
  examples/debugging/src/lib.rs
  packages/fuels-test-helpers/src/node_types.rs
  packages/fuels-test-helpers/src/service.rs
  packages/fuels/Forc.toml
  packages/fuels/tests/providers.rs
  packages/fuels/tests/types_contracts.rs
Labels: tech-debt

#1337 fix: receipt parsing when call is repeated through internal call
  docs/src/calling-contracts/cost-estimation.md
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/receipt_parser.rs
  packages/fuels-programs/src/script_calls.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/contracts/lib_contract_caller/src/main.sw
Labels: enhancement

#1339 chore: improve `b256` tests
  docs/src/types/bits256.md
  packages/fuels/Forc.toml
  packages/fuels/tests/bindings.rs
  packages/fuels/tests/scripts.rs
  packages/fuels/tests/types/contracts/b256/Forc.toml
  packages/fuels/tests/types/contracts/b256/src/main.sw
  packages/fuels/tests/types/contracts/vector_output/src/main.sw
  packages/fuels/tests/types/predicates/predicate_b256/Forc.toml
  packages/fuels/tests/types/predicates/predicate_b256/src/main.sw
  packages/fuels/tests/types/predicates/predicate_vectors/src/main.sw
  packages/fuels/tests/types/scripts/script_b256/Forc.toml
  packages/fuels/tests/types/scripts/script_b256/src/main.sw
  packages/fuels/tests/types/scripts/script_vectors/src/eq_impls.sw
  packages/fuels/tests/types/scripts/script_vectors/src/main.sw
  packages/fuels/tests/types_contracts.rs
  packages/fuels/tests/types_predicates.rs
  packages/fuels/tests/types_scripts.rs
Labels: tech-debt

#1348 feat: version incompatibility is now a soft warning
  packages/fuels-accounts/Cargo.toml
  packages/fuels-accounts/src/provider.rs
  packages/fuels-accounts/src/provider/retryable_client.rs
  packages/fuels-accounts/src/provider/supported_versions.rs
  packages/fuels/tests/providers.rs
Labels: enhancement
