Repository FuelLabs/fuels-rs, pull requests merged in 2024-08, with the labels that each got.

#1476 chore: enable testnet connection test
  examples/providers/src/lib.rs
Labels: documentation, tech-debt

#1472 feat!: deploying large contracts (loader + blob support)
  .github/workflows/ci.yml
  Cargo.toml
  docs/src/SUMMARY.md
  docs/src/deploying/large_contracts.md
  e2e/Forc.toml
  e2e/sway/contracts/huge_contract/Forc.toml
  e2e/sway/contracts/huge_contract/src/main.sw
  e2e/tests/configurables.rs
  e2e/tests/contracts.rs
  e2e/tests/providers.rs
  e2e/tests/types_predicates.rs
  examples/contracts/Cargo.toml
  examples/contracts/src/lib.rs
  examples/providers/src/lib.rs
  packages/fuels-accounts/src/provider/supported_fuel_core_version.rs
  packages/fuels-code-gen/Cargo.toml
  packages/fuels-core/src/lib.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-core/src/types/transaction_builders/blob.rs
  packages/fuels-core/src/types/transaction_builders/script_tx_estimator.rs
  packages/fuels-core/src/types/wrappers/transaction.rs
  packages/fuels-core/src/types/wrappers/transaction_response.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/contract/load.rs
  packages/fuels-programs/src/contract/loader.rs
  packages/fuels-programs/src/contract/regular.rs
  packages/fuels-programs/src/contract/storage.rs
  packages/fuels-test-helpers/Cargo.toml
  packages/fuels-test-helpers/src/fuel_bin_service.rs
  packages/fuels-test-helpers/src/node_types.rs
  packages/fuels-test-helpers/src/service.rs
Labels: enhancement, breaking

#1480 feat: default gas estimation horizon in tx builders
  .github/workflows/ci.yml
  e2e/tests/providers.rs
  examples/contracts/src/lib.rs
  packages/fuels-accounts/src/provider/supported_fuel_core_version.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-core/src/types/transaction_builders/blob.rs
Labels: tech-debt

#1483 fix: string slice decoding
  packages/fuels-core/src/codec.rs
  packages/fuels-core/src/codec/abi_decoder/bounded_decoder.rs
Labels: bug

#1484 chore: bump fuel-core
  Cargo.toml
Labels: enhancement

#1487 chore: update `forc` to `0.63.1`
  .github/workflows/ci.yml
Labels: tech-debt

#1486 chore: bump fuel-core to 0.33.0
  .github/workflows/ci.yml
  Cargo.toml
  e2e/tests/providers.rs
  packages/fuels-accounts/src/provider/supported_fuel_core_version.rs
  packages/fuels-test-helpers/Cargo.toml
  packages/fuels-test-helpers/src/service.rs
  packages/fuels/Cargo.toml
Labels: enhancement

#1493 chore: remove patch
  e2e/Forc.toml
  e2e/sway/predicates/predicate_witnesses/src/main.sw
  e2e/sway/predicates/swap/src/main.sw
Labels: tech-debt

#1494 fix: state read dry run sets gas price to 0
  e2e/tests/contracts.rs
  packages/fuels-programs/src/calls/call_handler.rs
Labels: bug

#1495 docs: Add change log scripts
  .env.example
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  scripts/change-log/Cargo.toml
  scripts/change-log/src/get_full_changelog.rs
  scripts/change-log/src/get_latest_release.rs
  scripts/change-log/src/main.rs
Labels: documentation
