Repository FuelLabs/fuels-rs, pull requests merged in 2024-09, with the labels that each got.

#1497 chore: update `forc` to `0.63.3`
  .github/workflows/ci.yml
  e2e/tests/providers.rs
  examples/contracts/src/lib.rs
Labels: tech-debt

#1496 chore: update `fuel-core` to `0.35.0`
  .github/workflows/ci.yml
  Cargo.toml
  packages/fuels-accounts/src/provider/supported_fuel_core_version.rs
  packages/fuels-core/Cargo.toml
Labels: tech-debt

#1503 bug: fix code being shifted when loaded via LDC
  e2e/Forc.toml
  e2e/build.rs
  e2e/sway/contracts/proxy/Forc.toml
  e2e/sway/contracts/proxy/src/main.sw
  e2e/tests/contracts.rs
  packages/fuels-programs/src/contract/loader.rs
Labels: bug

#1340 chore: extend types tests with array with generics
  e2e/sway/types/contracts/generics/src/main.sw
  e2e/tests/types_contracts.rs
Labels: enhancement

#1500 chore: fix markdown reported by clippy in docs
  packages/fuels-code-gen/src/program_bindings/abigen.rs
  packages/fuels-programs/src/calls/call_handler.rs
Labels: documentation, tech-debt
