Repository FuelLabs/fuels-rs, pull requests merged in 2024-06, with the labels that each got.

#1411 docs: fix fuel specification links
  docs/src/calling-contracts/call-response.md
  docs/src/calling-contracts/variable-outputs.md
  docs/src/cli/fuels-abi-cli.md
  docs/src/codec/index.md
Labels: documentation

#1393 feat!: var output estimation optimization
  docs/src/calling-contracts/tx-dependency-estimation.md
  docs/src/calling-contracts/variable-outputs.md
  e2e/Forc.toml
  e2e/sway/contracts/var_outputs/Forc.toml
  e2e/sway/contracts/var_outputs/src/main.sw
  e2e/tests/contracts.rs
  e2e/tests/providers.rs
  e2e/tests/scripts.rs
  examples/contracts/src/lib.rs
  examples/cookbook/src/lib.rs
  packages/fuels-accounts/src/account.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-core/src/types/transaction_builders/dry_runner.rs
  packages/fuels-core/src/types/transaction_builders/script_dry_runner.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/script_calls.rs
Labels: enhancement

#1422 fix!: `dry_run` tx with non-zero base asset and tip
  e2e/tests/contracts.rs
  examples/contracts/src/lib.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-accounts/src/provider/retryable_client.rs
  packages/fuels-core/src/types/transaction_builders/script_dry_runner.rs
Labels: bug

#1425 fix!: filter already used inputs when adjusting for fee
  e2e/tests/contracts.rs
  e2e/tests/predicates.rs
  e2e/tests/providers.rs
  e2e/tests/scripts.rs
  e2e/tests/wallets.rs
  examples/cookbook/src/lib.rs
  packages/fuels-accounts/Cargo.toml
  packages/fuels-accounts/src/account.rs
  packages/fuels-accounts/src/accounts_utils.rs
  packages/fuels-accounts/src/predicate.rs
  packages/fuels-accounts/src/wallet.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-test-helpers/src/accounts.rs
Labels: bug, enhancement

#1426 fix: include witness data in estimation
  e2e/Cargo.toml
  e2e/tests/providers.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-core/src/types/transaction_builders/script_dry_runner.rs
Labels: bug, enhancement

#1428 fix: use fallback predicate estimation within transaction builder
  packages/fuels-accounts/src/account.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-core/src/types.rs
  packages/fuels-core/src/types/dry_runner.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-core/src/types/transaction_builders/script_dry_runner.rs
  packages/fuels-core/src/types/wrappers/transaction.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-programs/src/script_calls.rs
Labels: bug

#1435 feat: use fallback predicate estimation in `set_max_fee_policy`
  packages/fuels-accounts/src/provider.rs
  packages/fuels-core/src/types/transaction_builders.rs
Labels: tech-debt

#1402 refactor!: unify call handlers to `CallHandler`
  docs/src/calling-contracts/call-response.md
  docs/src/calling-contracts/cost-estimation.md
  docs/src/calling-contracts/logs.md
  docs/src/calling-contracts/multicalls.md
  docs/src/calling-contracts/other-contracts.md
  docs/src/custom-transactions/custom-calls.md
  e2e/build.rs
  e2e/tests/bindings.rs
  e2e/tests/contracts.rs
  e2e/tests/logs.rs
  examples/contracts/src/lib.rs
  examples/rust_bindings/src/rust_bindings_formatted.rs
  packages/fuels-accounts/src/provider/supported_versions.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/contract.rs
  packages/fuels-code-gen/src/program_bindings/abigen/bindings/script.rs
  packages/fuels-core/src/types/errors.rs
  packages/fuels-core/src/utils/offsets.rs
  packages/fuels-programs/src/calls.rs
  packages/fuels-programs/src/calls/call_handler.rs
  packages/fuels-programs/src/calls/contract_call.rs
  packages/fuels-programs/src/calls/receipt_parser.rs
  packages/fuels-programs/src/calls/script_call.rs
  packages/fuels-programs/src/calls/traits.rs
  packages/fuels-programs/src/calls/traits/contract_dep_configurator.rs
  packages/fuels-programs/src/calls/traits/response_parser.rs
  packages/fuels-programs/src/calls/traits/transaction_tuner.rs
  packages/fuels-programs/src/calls/utils.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/contract/load.rs
  packages/fuels-programs/src/contract/storage.rs
  packages/fuels-programs/src/lib.rs
  packages/fuels-programs/src/responses.rs
  packages/fuels-programs/src/responses/call.rs
  packages/fuels-programs/src/responses/submit.rs
  packages/fuels-programs/src/script_calls.rs
  packages/fuels-programs/src/submit_response.rs
  packages/fuels/src/lib.rs
Labels: big, breaking

#1421 chore: add editorconfig for TOML
  .editorconfig
Labels: enhancement, tech-debt

#1396 feat!: support static gas price setting in `NodeConfig`
  docs/src/cookbook/transfer-all-assets.md
  e2e/tests/predicates.rs
  e2e/tests/providers.rs
  e2e/tests/types_predicates.rs
  e2e/tests/wallets.rs
  examples/cookbook/src/lib.rs
  examples/predicates/src/lib.rs
  examples/wallets/src/lib.rs
  packages/fuels-test-helpers/src/accounts.rs
  packages/fuels-test-helpers/src/fuel_bin_service.rs
  packages/fuels-test-helpers/src/node_types.rs
  packages/fuels-test-helpers/src/service.rs
Labels: bug, enhancement

#1450 chore: use fuel publish action
  .github/workflows/ci.yml
Labels: tech-debt

#1452 docs: fix testnet and faucet link
  docs/src/connecting/external-node.md
  examples/providers/src/lib.rs
Labels: documentation
