Repository FuelLabs/fuels-rs, pull requests merged in 2024-03, with the labels that each got.

#1291 feat!: add `decode_as_debug_str` to `ABIDecoder`
  examples/debugging/src/lib.rs
  packages/fuels-core/src/codec/abi_decoder.rs
  packages/fuels-core/src/codec/abi_decoder/bounded_decoder.rs
  packages/fuels-core/src/codec/abi_decoder/decode_as_debug_str.rs
  packages/fuels-core/src/codec/abi_decoder/experimental_bounded_decoder.rs
  packages/fuels-core/src/codec/abi_encoder.rs
  packages/fuels-core/src/codec/abi_encoder/bounded_encoder.rs
  packages/fuels-core/src/codec/function_selector.rs
  packages/fuels-core/src/traits/parameterize.rs
  packages/fuels-core/src/traits/tokenizable.rs
  packages/fuels-core/src/types.rs
  packages/fuels-core/src/types/core/bits.rs
  packages/fuels-core/src/types/param_types.rs
  packages/fuels-core/src/types/param_types/debug_with_depth.rs
  packages/fuels-core/src/types/param_types/enum_variants.rs
  packages/fuels-core/src/types/param_types/from_type_application.rs
  packages/fuels-core/src/types/param_types/param_type.rs
  packages/fuels-core/src/utils.rs
  packages/fuels-macros/src/derive/parameterize.rs
  packages/fuels-macros/src/derive/tokenizable.rs
  packages/fuels-macros/src/parse_utils.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels/tests/types/contracts/generics/src/main.sw
  packages/fuels/tests/types_contracts.rs
Labels: tech-debt, dev-experience

#1295 docs: expand converting types page
  docs/src/SUMMARY.md
  docs/src/types/conversion.md
  examples/types/src/lib.rs
  examples/wallets/src/lib.rs
  packages/fuels-core/src/types/core/bits.rs
  packages/fuels-core/src/types/core/bytes.rs
  packages/fuels/tests/logs.rs
Labels: documentation

#1294 fix: configurables encoding to have top level u8 and bool single-byte optimizations
  packages/fuels-code-gen/src/program_bindings/abigen/configurables.rs
  packages/fuels-core/Cargo.toml
  packages/fuels-core/src/codec/abi_encoder.rs
  packages/fuels-core/src/codec/abi_encoder/bounded_encoder.rs
  packages/fuels/tests/configurables.rs
Labels: bug

#1292 feat!: update `fuel-core` to `0.23.0`
  .github/workflows/ci.yml
  Cargo.toml
  docs/src/calling-contracts/cost-estimation.md
  docs/src/calling-contracts/tx-policies.md
  examples/contracts/src/lib.rs
  examples/cookbook/src/lib.rs
  packages/fuels-accounts/Cargo.toml
  packages/fuels-accounts/src/account.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-accounts/src/provider/retryable_client.rs
  packages/fuels-accounts/src/provider/supported_versions.rs
  packages/fuels-core/src/types.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-core/src/types/wrappers.rs
  packages/fuels-core/src/types/wrappers/coin.rs
  packages/fuels-core/src/types/wrappers/transaction.rs
  packages/fuels-core/src/types/wrappers/transaction_response.rs
  packages/fuels-core/src/utils/constants.rs
  packages/fuels-programs/src/call_utils.rs
  packages/fuels-programs/src/contract.rs
  packages/fuels-programs/src/script_calls.rs
  packages/fuels-test-helpers/src/lib.rs
  packages/fuels/tests/contracts.rs
  packages/fuels/tests/predicates.rs
  packages/fuels/tests/providers.rs
  packages/fuels/tests/scripts.rs
  packages/fuels/tests/wallets.rs
Labels: tech-debt, breaking

#1304 chore: bump `rust` to `1.76.0`
  .github/workflows/ci.yml
  Cargo.toml
Labels: tech-debt

#1258 chore: add test for trig never
  packages/fuels/tests/providers.rs
Labels: tech-debt

#1302 fix: transaction builder `no_input_to_cover_fees`
  examples/types/src/lib.rs
  packages/fuels-core/src/types/transaction_builders.rs
Labels: bug
