Repository FuelLabs/fuels-rs, pull requests merged in 2025-02, with the labels that each got.

#1586 fix: message with data exluded in `adjust_for_fee`
  e2e/tests/predicates.rs
  e2e/tests/wallets.rs
  packages/fuels-accounts/src/accounts_utils.rs
Labels: bug

#1592 bug: backport max fee fix to LTS 0.70
  .github/workflows/ci.yml
  e2e/sway/contracts/lib_contract/Forc.toml
  e2e/sway/contracts/lib_contract/src/main.sw
  e2e/sway/logs/contract_logs/Forc.toml
  e2e/sway/logs/contract_logs/src/main.sw
  e2e/sway/predicates/swap/src/main.sw
  e2e/tests/contracts.rs
  e2e/tests/debug_utils.rs
  e2e/tests/providers.rs
  e2e/tests/scripts.rs
  e2e/tests/types_predicates.rs
  e2e/tests/wallets.rs
  examples/contracts/src/lib.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-accounts/src/schema/schema.sdl
  packages/fuels-core/src/types/dry_runner.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-programs/src/calls/traits/transaction_tuner.rs
  packages/fuels-programs/src/calls/utils.rs
  packages/fuels-programs/src/contract/loader.rs
  packages/fuels-programs/src/contract/regular.rs
  packages/fuels-programs/src/executable.rs
  packages/fuels-programs/src/lib.rs
  packages/fuels-test-helpers/Cargo.toml
  packages/fuels-test-helpers/src/service.rs
Labels: bug

#1583 feat: add `expiration` transaction policy
  docs/src/calling-contracts/tx-policies.md
  docs/src/custom-transactions/transaction-builders.md
  e2e/tests/contracts.rs
  e2e/tests/predicates.rs
  e2e/tests/providers.rs
  e2e/tests/scripts.rs
  e2e/tests/wallets.rs
  examples/contracts/src/lib.rs
  examples/cookbook/src/lib.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-core/src/types/wrappers/transaction.rs
Labels: enhancement

#1595 feat: add context to `Result`
  packages/fuels-core/src/types/errors.rs
Labels: enhancement

#1593 feat: switch blob ID calculation from data offset to configurable offset
  e2e/assets/precompiled_sway/legacy_format_simple_contract.bin
  e2e/tests/binary_format.rs
  e2e/tests/debug_utils.rs
  e2e/tests/scripts.rs
  packages/fuels-programs/src/assembly/contract_call.rs
  packages/fuels-programs/src/assembly/script_and_predicate_loader.rs
  packages/fuels-programs/src/debug.rs
  packages/fuels-programs/src/executable.rs
  scripts/change-log/src/get_full_changelog.rs
Labels: enhancement

#1601 chore: update sway's counter example
  e2e/sway/contracts/contract_test/src/main.sw
  e2e/tests/contracts.rs
  examples/contracts/src/lib.rs
Labels: enhancement

#1602 feat: changelog generator for LTS releases
  Cargo.toml
  scripts/change-log/Cargo.toml
  scripts/change-log/src/adapters.rs
  scripts/change-log/src/adapters/octocrab.rs
  scripts/change-log/src/domain.rs
  scripts/change-log/src/domain/changelog.rs
  scripts/change-log/src/domain/models.rs
  scripts/change-log/src/get_full_changelog.rs
  scripts/change-log/src/get_latest_release.rs
  scripts/change-log/src/lib.rs
  scripts/change-log/src/main.rs
  scripts/change-log/src/ports.rs
  scripts/change-log/src/ports/github.rs
Labels: enhancement

#1574 feat!: use `total_gas` and `total_fee` from tx status
  docs/src/calling-contracts/cost-estimation.md
  e2e/tests/configurables.rs
  e2e/tests/contracts.rs
  e2e/tests/logs.rs
  e2e/tests/predicates.rs
  e2e/tests/providers.rs
  e2e/tests/scripts.rs
  e2e/tests/storage.rs
  e2e/tests/types_contracts.rs
  e2e/tests/types_predicates.rs
  e2e/tests/wallets.rs
  examples/contracts/src/lib.rs
  examples/cookbook/src/lib.rs
  examples/wallets/src/lib.rs
  packages/fuels-accounts/src/account.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-core/src/types.rs
  packages/fuels-core/src/types/tx_response.rs
  packages/fuels-core/src/types/tx_status.rs
  packages/fuels-core/src/types/wrappers/transaction.rs
  packages/fuels-macros/src/setup_program_test/code_gen.rs
  packages/fuels-programs/src/calls/call_handler.rs
  packages/fuels-programs/src/contract/loader.rs
  packages/fuels-programs/src/contract/regular.rs
  packages/fuels-programs/src/executable.rs
  packages/fuels-programs/src/responses/call.rs
  packages/fuels-programs/src/responses/submit.rs
Labels: tech-debt
