Repository FuelLabs/fuels-rs, pull requests merged in 2025-01, with the labels that each got.

#1569 bug!: updating consensus parameters
  Cargo.toml
  e2e/tests/contracts.rs
  e2e/tests/predicates.rs
  e2e/tests/providers.rs
  e2e/tests/wallets.rs
  examples/contracts/src/lib.rs
  examples/cookbook/src/lib.rs
  examples/providers/src/lib.rs
  packages/fuels-accounts/Cargo.toml
  packages/fuels-accounts/src/account.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-accounts/src/provider/cache.rs
  packages/fuels-accounts/src/provider/retryable_client.rs
  packages/fuels-core/src/types/dry_runner.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-core/src/types/transaction_builders/blob.rs
  packages/fuels-core/src/types/transaction_builders/script_tx_estimator.rs
  packages/fuels-programs/src/calls/call_handler.rs
  packages/fuels-programs/src/calls/utils.rs
  packages/fuels-programs/src/contract/regular.rs
  packages/fuels-test-helpers/src/accounts.rs
  packages/fuels-test-helpers/src/lib.rs
Labels: bug

#1570 chore: nits from previous PR
  packages/fuels-accounts/src/provider.rs
  packages/fuels-accounts/src/provider/cache.rs
Labels: tech-debt

#1571 chore!: remove option return from predicate estimation
  packages/fuels-accounts/src/account.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-core/src/types/dry_runner.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-core/src/types/wrappers/transaction.rs
Labels: tech-debt

#1499 feat!: gracefully handle unknown transaction variants
  .github/workflows/ci.yml
  Cargo.toml
  e2e/tests/contracts.rs
  e2e/tests/predicates.rs
  e2e/tests/providers.rs
  e2e/tests/types_predicates.rs
  e2e/tests/wallets.rs
  examples/cookbook/src/lib.rs
  examples/wallets/src/lib.rs
  packages/fuels-accounts/src/account.rs
  packages/fuels-accounts/src/accounts_utils.rs
  packages/fuels-accounts/src/impersonated_account.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-accounts/src/provider/retryable_client.rs
  packages/fuels-accounts/src/provider/supported_fuel_core_version.rs
  packages/fuels-accounts/src/schema/schema.sdl
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-core/src/types/wrappers/coin_type.rs
  packages/fuels-core/src/types/wrappers/transaction.rs
  packages/fuels-core/src/types/wrappers/transaction_response.rs
  packages/fuels-programs/src/calls/utils.rs
  packages/fuels-test-helpers/Cargo.toml
  packages/fuels-test-helpers/src/accounts.rs
  packages/fuels-test-helpers/src/node_types.rs
  packages/fuels-test-helpers/src/service.rs
Labels: breaking

#1573 feat: use `blob_exists` endpoint before uploading contract blob
  packages/fuels-programs/src/contract/loader.rs
Labels: tech-debt

#1590 bug: script/predicate blob upload now uses the default max fee estimation tolerance
  e2e/tests/contracts.rs
  e2e/tests/scripts.rs
  packages/fuels-accounts/src/provider.rs
  packages/fuels-core/src/types/dry_runner.rs
  packages/fuels-core/src/types/transaction_builders.rs
  packages/fuels-programs/src/calls/traits/transaction_tuner.rs
  packages/fuels-programs/src/calls/utils.rs
  packages/fuels-programs/src/contract/loader.rs
  packages/fuels-programs/src/contract/regular.rs
  packages/fuels-programs/src/executable.rs
  packages/fuels-programs/src/lib.rs
Labels: bug
